export interface ServiceFaq {
  question: string;
  answer: string;
}

export interface ServiceStep {
  title: string;
  detail: string;
}

export interface ServiceTable {
  title: string;
  caption?: string;
  columns: string[];
  rows: string[][];
}

export interface ServiceTab {
  label: string;
  title: string;
  detail: string;
  points: string[];
}

export interface ServicePageContent {
  title: string;
  eyebrow: string;
  description: string;
  heroMetric: string;
  heroLabel: string;
  introTitle: string;
  intro: string;
  metrics: { value: string; label: string }[];
  highlights: { title: string; description: string }[];
  processTitle: string;
  process: ServiceStep[];
  documentsTitle: string;
  documents: string[];
  faqs: ServiceFaq[];
  notice?: { title: string; text: string; tone?: 'warning' | 'info' };
  table?: ServiceTable;
  benefits?: { title: string; description: string }[];
  tags?: { title: string; values: string[] }[];
  tabs?: ServiceTab[];
  interaction?: 'golden' | 'attestation' | 'visa-checker' | 'locations' | 'translation' | 'poa' | 'iloe';
  formTitle: string;
  formDescription: string;
}

export const serviceCatalog: Record<string, ServicePageContent> = {
  'Family Visa': {
    title: 'Family Visa',
    eyebrow: 'UAE family residence',
    description: 'Bring your family to the UAE with a clear, case-checked plan for sponsorship, attestation, entry permits and residence formalities.',
    heroMetric: 'AED 4,000',
    heroLabel: 'general monthly sponsor salary',
    introTitle: 'A well-prepared family file starts with the sponsor',
    intro: 'Spouse and child sponsorship usually begins with a UAE-resident sponsor, proof of the family relationship and evidence of qualifying income. Parents have higher income and accommodation requirements. Eligibility and final fees vary by emirate, relationship and current authority rules, so confirm the case before submitting.',
    metrics: [{ value: 'AED 4,000', label: 'salary, or AED 3,000 with employer housing' }, { value: '5–10 days', label: 'typical new application, after documents are ready' }, { value: '120 days', label: 'newborn residence deadline from birth' }],
    highlights: [
      { title: 'Sponsor salary', description: 'AED 4,000 monthly, or AED 3,000 where the employer provides accommodation, is the general spouse-and-child threshold.' },
      { title: 'Parents need a separate review', description: 'Parent sponsorship is commonly assessed around AED 20,000 monthly, with suitable housing, insurance and additional conditions.' },
      { title: 'Attested relationship proof', description: 'Foreign marriage and birth certificates need the required home-country and UAE attestations, followed by certified Arabic translation.' },
    ],
    processTitle: 'From entry permit to residence visa',
    process: [
      { title: 'Open or update the family file', detail: 'Check sponsor eligibility, attest relationship certificates and submit the dependent residence entry-permit application.' },
      { title: 'Enter or change status', detail: 'The dependent enters on the permit, or applies for an in-country status change when eligible.' },
      { title: 'Medical fitness & Emirates ID', detail: 'Adult dependents complete medical fitness screening and the Emirates ID application/biometrics.' },
      { title: 'Residence issuance', detail: 'After the required approvals and fees, the electronic residence permit is issued and linked to the Emirates ID.' },
    ],
    documentsTitle: 'Family sponsorship document checklist',
    documents: ['Sponsor passport, UAE residence and Emirates ID', 'Sponsor salary certificate or labour contract and accommodation proof where applicable', 'Dependent passport copy with required validity and a recent photo', 'Attested marriage certificate for a spouse or birth certificate for a child', 'Tenancy contract / Ejari and health insurance where required', 'Application number, entry permit or previous visa for an in-country status change'],
    faqs: [
      { question: 'Can a wife sponsor her husband and children?', answer: 'Yes. A UAE-resident woman can sponsor eligible family members when she meets the applicable income and occupation conditions. The authority may request additional evidence, so check the file before lodging it.' },
      { question: 'Does a family member on a visit visa need to leave the UAE?', answer: 'Often an in-country change-of-status application can be used instead of exit and re-entry. The correct route depends on the visa and current authority rules.' },
      { question: 'How much does family visa processing cost?', answer: 'Government, medical, Emirates ID, insurance and service-centre charges depend on visa duration, emirate and whether the family file is new. Ask for an itemised quote before payment.' },
      { question: 'Do foreign certificates need attestation?', answer: 'Marriage and birth records generally require the issuing-country chain of attestation, UAE Embassy attestation and UAE MOFA attestation, plus certified Arabic translation.' },
    ],
    formTitle: 'Check your family sponsorship eligibility',
    formDescription: 'Share the sponsor emirate, relationship and intended visa route for a tailored document list and itemised estimate.',
    table: {
      title: 'Family visa cost breakdown',
      caption: 'Fees vary by emirate, visa duration and whether a family file is already open. Ask for a current quote with government charges and optional services separated.',
      columns: ['Cost item', 'When it applies', 'How it is quoted'],
      rows: [
        ['Family file opening', 'First time sponsoring a dependent', 'One-time government fee'],
        ['Entry permit / status change', 'New dependent or applicant already in the UAE', 'Government fee by route'],
        ['Medical fitness & Emirates ID', 'Adult dependent applications; child steps differ', 'Government fees by age and visa duration'],
        ['Health insurance', 'Where required for the emirate and dependent category', 'Policy premium based on cover and age'],
        ['Attestation & Arabic translation', 'Foreign marriage or birth certificate', 'Quoted separately by document and country'],
        ['Typing / professional service', 'Optional application preparation and follow-up', 'Service fee shown separately from government costs'],
      ],
    },
  },
  'Golden Visa': {
    title: 'Golden Visa',
    eyebrow: 'Long-term UAE residency',
    description: 'Explore the right 10-year residency route, compare category requirements and prepare the evidence before starting a nomination or application.',
    heroMetric: '10 YEARS',
    heroLabel: 'long-term residency route',
    introTitle: 'Start with the strongest qualifying category',
    intro: 'Golden Visa eligibility is category-specific. Dubai real-estate investors, skilled professionals, entrepreneurs and high-achieving students rely on different evidence and approval channels. Use the guide below to narrow your route, then confirm current criteria with the relevant authority before making financial decisions.',
    metrics: [{ value: 'AED 2M+', label: 'qualifying Dubai property value route' }, { value: '10 years', label: 'residence validity, subject to category approval' }, { value: 'Family', label: 'eligible dependents can be sponsored' }],
    highlights: [
      { title: 'Route-first advice', description: 'A category review checks whether property, professional, entrepreneur or student evidence is the best fit.' },
      { title: 'Application sequencing', description: 'Coordinate nomination, document attestation, medical fitness and Emirates ID without cancelling existing status prematurely.' },
      { title: 'Family planning', description: 'Plan eligible spouse, children and other dependents alongside the main applicant file.' },
    ],
    processTitle: 'A considered route from eligibility to residency',
    process: [
      { title: 'Eligibility screener', detail: 'Select the closest route and provide the relevant profile details to prepare for an advisor review.' },
      { title: 'Evidence and nomination', detail: 'Collect category-specific proof and submit the nomination or initial application through the correct authority channel.' },
      { title: 'Medical and biometrics', detail: 'After the required approval, complete medical fitness and Emirates ID formalities in the UAE.' },
      { title: 'Residence issuance', detail: 'Complete the final authority steps and coordinate eligible family applications.' },
    ],
    documentsTitle: 'Core documents to prepare',
    documents: ['Passport and current UAE visa / Emirates ID if resident', 'Recent photograph and contact details', 'Property title deed and DLD valuation, or salary / employment evidence, as relevant', 'Attested degree and professional licence for applicable skilled-professional routes', 'Company licence, ownership or investment records for entrepreneur routes', 'Student transcripts, graduation evidence and recommendation where applicable'],
    faqs: [
      { question: 'Does a mortgaged property count toward AED 2 million?', answer: 'The property value is generally assessed rather than only the applicant’s equity. A current DLD valuation may help when the historical title-deed value is outdated; confirm the individual file.' },
      { question: 'Does a salary package above AED 30,000 qualify?', answer: 'For the salaried professional route, the basic salary on the labour contract may be assessed, along with occupation, qualification and authority criteria. Other categories may fit better.' },
      { question: 'Do I have to cancel my current visa first?', answer: 'Do not cancel a current residence visa until the correct sequence is confirmed. The existing status is commonly retained until pre-approval or the authority directs otherwise.' },
      { question: 'Can I apply while outside the UAE?', answer: 'Some property nominations can be initiated from abroad, with an entry permit issued for required in-country steps. Other routes may require UAE residence.' },
    ],
    tabs: [
      { label: 'Property investors', title: 'Real estate investors', detail: 'A Dubai property investment valued at AED 2 million or more may qualify for a 10-year Golden Visa route, subject to DLD and immigration review.', points: ['Title deed or eligible off-plan ownership proof', 'DLD valuation where required', 'Mortgage and joint-ownership evidence if applicable'] },
      { label: 'Professionals', title: 'High earners & professionals', detail: 'Skilled professionals may qualify based on role, salary, degree, professional licence and employer documentation. The required combination depends on current rules.', points: ['Labour contract and salary certificate', 'Attested university degree', 'Valid professional licence where applicable'] },
      { label: 'Entrepreneurs', title: 'Entrepreneurs', detail: 'Entrepreneur routes assess the business, investment, project or approved incubator evidence against category-specific nomination criteria.', points: ['Trade licence and ownership records', 'Project, investment or incubator evidence', 'Approvals and recommendation letters where required'] },
      { label: 'Students', title: 'Outstanding students', detail: 'High-performing school and university graduates may be nominated based on academic achievement, institution and authority criteria.', points: ['Official transcripts and graduation certificate', 'School / university recommendation', 'Passport and current residence details'] },
    ],
    benefits: [
      { title: 'Long-term security', description: 'Residence validity of up to ten years, subject to the qualifying category and ongoing conditions.' },
      { title: 'Family sponsorship', description: 'Sponsor eligible family members under the applicable Golden Visa rules.' },
      { title: 'Flexible residency', description: 'Long-term residence designed for investors, professionals, entrepreneurs and exceptional students.' },
      { title: 'Business continuity', description: 'Plan personal residence and business commitments together with fewer short-term renewal cycles.' },
    ],
    interaction: 'golden',
    formTitle: 'Book a Golden Visa route review',
    formDescription: 'Tell us which category you are considering and an advisor can map the documents, authorities and next steps.',
  },
  'Property Visa': {
    title: 'Property Visa',
    eyebrow: 'Property-linked residency',
    description: 'Compare Dubai’s property investor and Golden Visa pathways, verify ownership evidence and coordinate the DLD and immigration stages.',
    heroMetric: 'AED 2M+',
    heroLabel: 'property value route for 10-year Golden Visa',
    introTitle: 'Choose the route that matches the ownership record',
    intro: 'Property value, title type, co-ownership, age and the issuing authority determine the available residence route. An SPA alone is not proof of registered ownership for visa purposes; use a DLD title deed or eligible Oqood and confirm the current threshold before you proceed.',
    metrics: [{ value: 'AED 2M+', label: '10-year Golden Visa property route' }, { value: 'No minimum*', label: 'sole-owner 2-year investor route; joint share above AED 400K' }, { value: 'DLD review', label: 'route and ownership evidence dependent' }],
    highlights: [
      { title: '10-year Golden Visa', description: 'A Dubai property or combined eligible property value of AED 2 million or more may qualify, subject to the authority’s review.' },
      { title: '2-year investor residence', description: 'The reference route describes no minimum property value for a sole owner and a joint ownership share above AED 400,000; title and current DLD criteria must be confirmed.' },
      { title: 'Retirement route', description: 'Applicants aged 55 or older may have a separate 5-year retirement route based on qualifying property value and additional conditions.' },
    ],
    processTitle: 'Dubai Land Department to residence issuance',
    process: [
      { title: 'Title and value review', detail: 'Confirm DLD ownership, title type, current valuation, ownership share and mortgage status.' },
      { title: 'DLD eligibility / nomination', detail: 'Submit the property evidence to the relevant DLD channel for eligibility confirmation or nomination.' },
      { title: 'Immigration application', detail: 'Prepare the entry permit or status-change file with the required personal and property documents.' },
      { title: 'Medical, ID and residence', detail: 'Complete medical fitness and Emirates ID steps, then finalize the residence permit.' },
    ],
    documentsTitle: 'Property and applicant checklist',
    documents: ['DLD Title Deed for a ready property or eligible Oqood for off-plan ownership', 'Current DLD valuation certificate if the recorded value needs updating', 'Passport, UAE visa / Emirates ID and recent photograph', 'Mortgage liability letter and bank NOC / no-objection evidence when required', 'Co-owner identity and share evidence for jointly held property', 'Proof of insurance and any dependent documents for family applications'],
    table: {
      title: 'Property visa routes at a glance',
      caption: 'Thresholds are route guides, not a guarantee of approval. Confirm the current DLD and immigration criteria before applying.',
      columns: ['Route', 'Property value / share', 'Validity', 'Key evidence'],
      rows: [
        ['Investor residence', 'No minimum for sole owner; joint share above AED 400,000 (reference guide)', '2 years', 'DLD ownership proof; title, status and current criteria apply'],
        ['Golden Visa', 'AED 2,000,000+', '10 years', 'Title deed / eligible Oqood; DLD valuation or mortgage evidence if needed'],
        ['Retirement residence', 'AED 1,000,000+; applicant aged 55+', '5 years', 'Property evidence and age / other eligibility requirements'],
      ],
    },
    faqs: [
      { question: 'Is an SPA enough for a property visa?', answer: 'No. The application needs DLD-issued ownership evidence such as a title deed for a ready property or eligible Oqood for an off-plan property.' },
      { question: 'Can I combine multiple properties?', answer: 'Eligible property values may be combined for certain routes when the DLD confirms ownership and total value.' },
      { question: 'Can my family apply with me?', answer: 'Eligible dependents can generally be sponsored. Their files require relationship documents and separate government charges.' },
      { question: 'Is the whole process online?', answer: 'Document review and many submissions can be handled remotely, but applicants still need to attend required medical and Emirates ID biometric appointments.' },
    ],
    formTitle: 'Check your property visa route',
    formDescription: 'Share the title type, ownership share and approximate current value for a route and document review.',
  },
  'Newborn Visa': {
    title: 'Newborn Visa',
    eyebrow: 'New arrival, clear steps',
    description: 'A practical newborn residence timeline that keeps birth registration, passport issuance, Emirates ID and visa filing on track.',
    heroMetric: '120 DAYS',
    heroLabel: 'residence application deadline from birth',
    introTitle: 'Start the newborn file as soon as the birth is registered',
    intro: 'A newborn born in the UAE must have a residence visa arranged within 120 days from the date of birth. The deadline covers the full chain from birth certificate and attestations to passport and residence processing. Start early; daily fines may apply after the grace period.',
    metrics: [{ value: 'Day 1–14', label: 'recommended time to begin document preparation' }, { value: '120 days', label: 'deadline counted from birth date' }, { value: '3 stages', label: 'certificate, passport, residence formalities' }],
    notice: { title: '120-day deadline: counted from the date of birth', text: 'Do not wait until the passport is issued to start. Birth certificate, required attestation, passport issuance, Emirates ID and visa steps must all be completed within the allowed period.', tone: 'warning' },
    highlights: [
      { title: 'Certificate first', description: 'Obtain the UAE birth certificate and confirm whether it needs MOFA attestation for your parents’ nationality and embassy process.' },
      { title: 'Passport application', description: 'Apply through the relevant embassy or consulate and check the photo, parent-ID and certificate rules early.' },
      { title: 'Fine prevention', description: 'Track the 120-day deadline from the birth date and keep proof of appointments and submissions in one file.' },
    ],
    processTitle: 'Newborn registration timeline',
    process: [
      { title: 'Birth certificate & attestation', detail: 'Register the birth, obtain the official certificate and complete any required embassy / MOFA attestation.' },
      { title: 'Newborn passport', detail: 'Submit the certificate and parent documents to the relevant embassy or consulate for passport issuance.' },
      { title: 'Dependent entry permit', detail: 'Prepare the sponsor and relationship file and apply for the newborn residence entry permit or status change.' },
      { title: 'Emirates ID & residence', detail: 'Complete the newborn Emirates ID application and finalize residence issuance before the deadline.' },
    ],
    documentsTitle: 'Newborn visa document checklist',
    documents: ['UAE birth certificate and attestation receipts where required', 'Newborn passport and recent passport-format photograph', 'Passports, UAE residence visas and Emirates IDs of both parents', 'Attested marriage certificate if requested by the authority', 'Sponsor salary and accommodation evidence where applicable', 'Application / entry permit number and newborn Emirates ID application'],
    faqs: [
      { question: 'When does the 120-day period start?', answer: 'It is counted from the newborn’s date of birth, not from passport collection or certificate attestation.' },
      { question: 'What happens if the deadline is missed?', answer: 'Overstay fines may apply after the applicable grace period. Contact the relevant authority or an authorized typing centre promptly to verify the file and current amount.' },
      { question: 'Does the newborn need medical fitness?', answer: 'Medical fitness requirements differ by age and application route. Newborns are generally handled differently from adult applicants; confirm the exact steps for your file.' },
      { question: 'Can we start before the passport arrives?', answer: 'Yes. Start preparing the birth certificate, parent records and attestation steps immediately while the passport application is underway.' },
    ],
    formTitle: 'Get a newborn deadline check',
    formDescription: 'Share the birth date, parents’ visa emirate and current document stage to prioritize the next steps.',
  },
  'Maid Visa': {
    title: 'Maid Visa',
    eyebrow: 'Domestic worker sponsorship',
    description: 'Understand sponsor eligibility, deposit and government-cost items, then coordinate domestic worker entry, medical, labour and residence steps.',
    heroMetric: 'ONE FILE',
    heroLabel: 'entry permit through residence issuance',
    introTitle: 'Household sponsorship has specific sponsor and worker conditions',
    intro: 'Domestic worker sponsorship requirements depend on the sponsor’s household status, income, accommodation, nationality and the worker’s circumstances. Salary thresholds and refundable deposits can change by route; get a current official, itemized quote before paying or recruiting.',
    metrics: [{ value: 'Sponsor review', label: 'income, family status and accommodation' }, { value: 'Itemized quote', label: 'government charges and refundable deposit separated' }, { value: 'End-to-end', label: 'permit, medical, contract and residence' }],
    highlights: [
      { title: 'Sponsor eligibility', description: 'Prepare salary evidence, family / marital status and suitable accommodation information for the applicable route.' },
      { title: 'Cost transparency', description: 'Separate government application, medical, Emirates ID, insurance, typing and any refundable deposit in the written quote.' },
      { title: 'Worker protections', description: 'Use the applicable approved channel and make sure contract, insurance and worker obligations are clear before travel.' },
    ],
    processTitle: 'Domestic worker typing and approval flow',
    process: [
      { title: 'Sponsor and worker eligibility', detail: 'Review the sponsor profile, household needs, worker passport and the route permitted for the case.' },
      { title: 'Entry permit & contract', detail: 'Submit the application and employment contract through the relevant authorized channel.' },
      { title: 'Medical & Emirates ID', detail: 'After arrival or status change, complete required medical fitness and Emirates ID formalities.' },
      { title: 'Residence issuance', detail: 'Pay the confirmed government charges, finalize the residence permit and retain receipts and contract records.' },
    ],
    documentsTitle: 'Sponsor and worker documents',
    documents: ['Sponsor passport, Emirates ID and UAE residence visa', 'Sponsor salary certificate / income evidence and accommodation documents', 'Family book or marriage certificate when relevant to eligibility', 'Worker passport, photograph and contact details', 'Signed domestic worker contract and any required job offer / insurance records', 'Application, medical and Emirates ID references after approval'],
    table: {
      title: 'Plan the full sponsorship cost',
      caption: 'Amounts vary by visa duration, emirate, worker route and current authority tariff. Request a dated quote and confirm which deposit is refundable.',
      columns: ['Cost item', 'What it covers', 'Quote treatment'],
      rows: [
        ['Entry permit / status change', 'Immigration application and in-country status change where applicable', 'Government fee'],
        ['Typing and approval', 'Authorized centre processing and contract / labour approvals', 'Government + centre service charge'],
        ['Medical fitness & Emirates ID', 'Required screening and identity-card application', 'Government / centre fee'],
        ['Insurance & refundable deposit', 'Required policy and any route-specific security deposit', 'Policy cost / refundable amount shown separately'],
        ['Residence issuance & service', 'Final residence permit and optional file-management support', 'Government fee + optional service fee'],
      ],
    },
    faqs: [
      { question: 'What is the minimum sponsor salary?', answer: 'There is no single threshold for every domestic-worker route. It depends on the sponsor category and current regulations; have the centre verify the current income requirement before starting.' },
      { question: 'Is a deposit always required?', answer: 'Some routes include a refundable deposit or guarantee. The amount and refund conditions differ, so request written confirmation and an official receipt.' },
      { question: 'Can the worker enter on a visit visa first?', answer: 'Do not treat a visit visa as permission to work. Use the authorized entry permit and employment process before work begins.' },
      { question: 'What is included in end-to-end support?', answer: 'Depending on the route: entry permit or status change, contract typing, medical fitness, Emirates ID and residence issuance coordination.' },
    ],
    formTitle: 'Request a domestic worker visa cost breakdown',
    formDescription: 'Tell us the sponsor emirate, household status and whether the worker is inside or outside the UAE.',
  },
  'Emirates ID': {
    title: 'Emirates ID Services',
    eyebrow: 'Federal identity services',
    description: 'Choose the right Emirates ID service—new application, renewal or replacement—and understand biometrics, tracking and delivery.',
    heroMetric: '3–5 DAYS',
    heroLabel: 'typical processing after application',
    introTitle: 'The right application depends on the cardholder’s status',
    intro: 'An Emirates ID is required for UAE residents of every age. Application type, residence validity, biometrics and delivery address determine the next steps. Use ICP’s official status service with your PRAN or application number for direct tracking.',
    metrics: [{ value: '24–48h', label: 'typical card printing after biometrics' }, { value: 'AED 150', label: 'optional Fawri fast service at ICP main centres' }, { value: '30 days', label: 'renewal grace period after expiry (confirm current rules)' }],
    highlights: [
      { title: 'New application', description: 'Usually linked to a new or renewed residence file; first-time adult applicants attend an ICP biometric appointment.' },
      { title: 'Renewal', description: 'Renew before or promptly after expiry. Biometrics may be reused when ICP does not request a new appointment.' },
      { title: 'Lost or damaged card', description: 'Report the loss / damage and apply for a replacement through ICP; protect your ID number and keep the request reference.' },
    ],
    processTitle: 'From application number to delivery',
    process: [
      { title: 'Select service type', detail: 'Choose a new, renewal or replacement application and check that the residence information is correct.' },
      { title: 'Submit and pay', detail: 'Complete the ICP application, upload the required records and keep the PRAN / application number.' },
      { title: 'Biometrics if requested', detail: 'Attend the designated ICP centre with the original passport and appointment confirmation.' },
      { title: 'Track and receive', detail: 'Check status on the ICP website or app; follow courier notifications for card delivery.' },
    ],
    documentsTitle: 'What to bring or upload',
    documents: ['Passport and valid residence visa / electronic residence details', 'Recent personal photograph meeting ICP specifications', 'Current Emirates ID for renewal or damaged-card replacement', 'PRAN / application reference for tracking', 'Parent or guardian Emirates ID and birth certificate for a child', 'Police report / loss declaration where required for a lost-card replacement'],
    table: {
      title: 'New, renewal or replacement?',
      caption: 'Final steps and fees depend on the cardholder category and ICP’s request.',
      columns: ['Service', 'Typical requirement', 'Biometrics', 'Tracking'],
      rows: [
        ['New application', 'Residence application / new eligibility, passport and photo', 'First-time adult applicants; child rules differ', 'PRAN on ICP website or app'],
        ['Renewal', 'Current ID, passport and valid / renewed residence details', 'Only if ICP requests it', 'PRAN or Emirates ID number'],
        ['Lost / damaged replacement', 'Identity evidence and replacement request; loss report if requested', 'May be requested for verification', 'Replacement application reference'],
      ],
    },
    faqs: [
      { question: 'How do I check my Emirates ID application?', answer: 'Use the official ICP website or UAE ICP app and enter your PRAN / application number. Status tracking is free.' },
      { question: 'Can children get an Emirates ID without fingerprints?', answer: 'Children under 15 generally do not provide fingerprints; the authority may require a photograph and guardian documents.' },
      { question: 'Can I apply while outside the UAE?', answer: 'Some renewals can be prepared remotely, but first-time applicants may need to be inside the UAE for biometrics. Confirm the appointment requirement with ICP.' },
      { question: 'When does the late renewal fine begin?', answer: 'The cited service guidance notes a 30-day grace period and AED 20 per day after that, capped at AED 1,000. Check current ICP rules for your case.' },
    ],
    formTitle: 'Need help with an Emirates ID application?',
    formDescription: 'Tell us whether it is a new card, renewal or replacement and include the application stage—not your full ID number.',
  },
  'PRO Services': {
    title: 'Corporate PRO Services',
    eyebrow: 'Corporate government relations',
    description: 'Outsource recurring UAE government transactions or request one-off individual PRO support with clear scope, ownership and reporting.',
    heroMetric: 'ON-DEMAND',
    heroLabel: 'PRO coverage for your business',
    introTitle: 'Keep business-critical government files moving',
    intro: 'A PRO coordinates government counters and digital systems across immigration, labour, typing, medical and Emirates ID services. A monthly retainer suits repeat company needs; one-off support can work better for an individual permit or a specific transaction. Government charges depend on the company’s MOHRE category and transaction type.',
    metrics: [{ value: 'MOHRE', label: 'labour permits and contracts' }, { value: 'GDRFA / ICP', label: 'residence and immigration files' }, { value: 'One-time or retainer', label: 'scope aligned to monthly volume' }],
    highlights: [
      { title: 'Corporate outsourcing', description: 'A named support team, renewal calendar and monthly tracker for visas, establishment cards, licences and employee lifecycle actions.' },
      { title: 'Individual PRO', description: 'Task-based assistance with an employee visa, dependent application, document attestation or a specific authority submission.' },
      { title: 'Clear fee separation', description: 'Government fees, centre charges, refundable deposits, VAT and professional service charges are listed separately.' },
    ],
    processTitle: 'From request to completed transaction',
    process: [
      { title: 'Scope and SLA', detail: 'Agree whether the request is a recurring retainer or a one-time transaction, including authorities, turnaround and reporting.' },
      { title: 'Establishment and file check', detail: 'Review trade licence, establishment card, MOHRE category and employee or sponsor records.' },
      { title: 'Submission and tracking', detail: 'Coordinate the required applications across MOHRE, GDRFA / ICP, medical fitness and Emirates ID channels.' },
      { title: 'Closure and calendar', detail: 'Share receipts and status updates, then schedule relevant renewals, cancellations or upcoming obligations.' },
    ],
    documentsTitle: 'Corporate onboarding checklist',
    documents: ['Valid trade licence and establishment / immigration card', 'Authorized signatory passport, Emirates ID and UAE Pass access where appropriate', 'MOHRE company category and quota details', 'Employee passport, photo, signed offer and qualification records as relevant', 'Current labour and residence records for renewals or cancellations', 'Company contact, escalation and approval matrix'],
    table: {
      title: 'Retainer or individual PRO support?',
      caption: 'The best model depends on transaction volume, company category and required response times.',
      columns: ['Model', 'Best for', 'Typical scope'],
      rows: [
        ['Corporate outsourcing', 'Companies with regular hiring, renewals and government submissions', 'Named coordinator, tracker, visa and permit lifecycle, establishment renewals'],
        ['Individual PRO service', 'A single employee, family or company transaction', 'Defined task, document review, application preparation and follow-up'],
        ['Project support', 'Licence change, quota planning or multi-employee onboarding', 'Time-bound plan, authority sequence and milestone reporting'],
      ],
    },
    faqs: [
      { question: 'Why does one company pay a different MOHRE labour fee?', answer: 'The company’s MOHRE category, employee profile and permit type affect labour charges. Confirm the live tariff and category before budgeting.' },
      { question: 'Can I hire someone who already has a family or Golden Visa?', answer: 'A work permit may be available without a new residence visa, subject to MOHRE rules and the employee’s status.' },
      { question: 'Can you process cancellations and renewals?', answer: 'Yes. The correct sequence depends on whether the worker remains in the UAE and the applicable employment settlement and immigration steps.' },
      { question: 'Are government fees included in the retainer?', answer: 'Government fees and third-party charges are usually separate from a professional service retainer and should be itemized in the proposal.' },
    ],
    formTitle: 'Discuss a corporate PRO retainer',
    formDescription: 'Share your company activity, employee count and expected monthly transactions for a scope proposal.',
  },
  'Amer Center': {
    title: 'Amer Center Services',
    eyebrow: 'Dubai immigration services',
    description: 'Prepare Dubai visa and residence transactions for submission through an authorized Amer centre or official GDRFA digital channels.',
    heroMetric: 'GDRFA',
    heroLabel: 'Dubai immigration authority',
    introTitle: 'Amer centres submit applications; GDRFA decides them',
    intro: 'An Amer centre is a privately operated service centre licensed by GDRFA Dubai to type and submit immigration applications. It is not itself a government office and cannot approve a visa. Federal ICP channels handle immigration matters for other emirates.',
    metrics: [{ value: 'Dubai only', label: 'Amer is the GDRFA Dubai service channel' }, { value: 'Walk-in', label: 'many centres accept walk-ins; hours vary' }, { value: 'Official channels', label: 'GDRFA website and smart app are available online' }],
    highlights: [
      { title: 'Residence & entry permits', description: 'Family, newborn, domestic worker, visit, Golden Visa, renewals, cancellations and change-of-status applications.' },
      { title: 'Company immigration', description: 'Establishment card and related immigration services, with separate labour transactions handled through MOHRE / Tasheel.' },
      { title: 'Express / VIP processing', description: 'Some centres offer a paid priority desk. It can shorten centre waiting time but does not guarantee government approval or processing speed.' },
    ],
    processTitle: 'Before you visit an Amer centre',
    process: [
      { title: 'Confirm the authority', detail: 'Use Amer for GDRFA Dubai cases. For visas issued by other emirates, check the federal ICP channel.' },
      { title: 'Ask for the exact checklist', detail: 'Requirements differ by transaction and sponsor; confirm originals, copies, photos and any attested certificates.' },
      { title: 'Submit and pay', detail: 'Review the application data before submission and ask for an itemized receipt separating government fees and centre charges.' },
      { title: 'Track with the reference', detail: 'Keep the application number and use official GDRFA channels to check for status or missing requirements.' },
    ],
    documentsTitle: 'General submission checklist',
    documents: ['Sponsor passport, Emirates ID and UAE visa copy', 'Applicant passport copy and recent white-background photo', 'Attested marriage / birth certificate and salary evidence for family cases', 'Trade licence and establishment card for company immigration requests', 'Application or previous file number for renewals and status change', 'Original documents requested for the specific service'],
    faqs: [
      { question: 'Is an Amer centre a government office?', answer: 'No. It is a private service centre licensed and supervised by GDRFA Dubai. GDRFA makes the immigration decision.' },
      { question: 'Can I visit an Amer centre outside Dubai?', answer: 'Amer is for GDRFA Dubai immigration services. Other emirates use federal ICP channels.' },
      { question: 'Do I need an appointment?', answer: 'Many centres accept walk-ins, but hours and appointment policies vary. Contact the selected centre before travelling.' },
      { question: 'How much will the centre charge?', answer: 'Government fees are set by the authority; each centre may charge a separate typing or service fee. Request an itemized quote and receipt.' },
    ],
    formTitle: 'Arrange an Amer appointment checklist',
    formDescription: 'Tell us the transaction type and visa emirate; we will confirm the likely documents and appropriate channel.',
  },
  'Attestation': {
    title: 'Document Attestation',
    eyebrow: 'UAE document legalization',
    description: 'Map the attestation chain for personal, educational or commercial records—from the issuing country through UAE MOFA.',
    heroMetric: 'MOFA UAE',
    heroLabel: 'final UAE attestation stage',
    introTitle: 'The attestation path depends on where a document was issued',
    intro: 'A document issued abroad usually needs verification in its country of origin, UAE Embassy / Consulate attestation and final UAE MOFA attestation. The exact sequence changes by country, document type, language and intended use. Confirm it before sending original documents.',
    metrics: [{ value: 'Country-specific', label: 'steps depend on document origin' }, { value: 'MOFA UAE', label: 'final UAE government attestation stage' }, { value: 'Arabic', label: 'certified translation when required for use' }],
    highlights: [
      { title: 'Educational', description: 'Degrees, diplomas and transcripts may need university, education authority and foreign-affairs verification before UAE Embassy and MOFA.' },
      { title: 'Personal', description: 'Birth, marriage, divorce and police certificates follow a country-specific chain and may need certified Arabic translation.' },
      { title: 'Commercial', description: 'Company, trade and corporate records require authority and chamber / notary stages appropriate to their place of issue.' },
    ],
    processTitle: 'Interactive attestation workflow',
    process: [
      { title: 'Issuing authority', detail: 'Confirm the original issuer and whether notarization, registrar or ministry authentication is required.' },
      { title: 'Home-country verification', detail: 'Complete the foreign-affairs / relevant authority stage in the country where the document was issued.' },
      { title: 'UAE Embassy / Consulate', detail: 'Obtain UAE diplomatic mission attestation in the document’s country of origin, if required.' },
      { title: 'MOFA UAE & translation', detail: 'Complete final MOFA UAE attestation and certified Arabic translation when needed for the intended transaction.' },
    ],
    documentsTitle: 'Before handing over a document',
    documents: ['Original document and a clear colour scan of every page', 'Passport copy of the document holder or authorized representative', 'Issuing country and city, issue date and document type', 'Intended UAE use: visa, court, school, employment, banking or business', 'Prior attestation stamps and certified translation, if already completed', 'Authorization letter if a third party will submit or collect the original'],
    faqs: [
      { question: 'Can the same attestation sequence be used for every country?', answer: 'No. The home-country chain varies by jurisdiction and document type. Verify the sequence with the UAE Embassy / Consulate and MOFA before submission.' },
      { question: 'When is Arabic translation required?', answer: 'It is often required for Arabic-language UAE authority, court or immigration use. The translator must meet the relevant certification requirements.' },
      { question: 'Can a copy be attested instead of the original?', answer: 'This depends on the document and authority. Many processes require the original or a certified true copy; confirm before dispatch.' },
      { question: 'Do company documents follow the personal-document route?', answer: 'No. Commercial records may require chamber, notary or corporate authority verification that does not apply to personal certificates.' },
    ],
    interaction: 'attestation',
    formTitle: 'Get a country-specific attestation sequence',
    formDescription: 'Choose the issuing country and document type above, then share the intended use for a tailored review.',
  },
  'Legal Translation': {
    title: 'Legal Translation',
    eyebrow: 'Ministry of Justice certified',
    description: 'Request a certified legal translation for court, notary, immigration, property and commercial use in the UAE.',
    heroMetric: 'MOJ',
    heroLabel: 'Ministry of Justice certified translation',
    introTitle: 'Legal wording, names and seals must carry through accurately',
    intro: 'Official use may require translation by a UAE Ministry of Justice licensed legal translator. Certification requirements vary by receiving authority and document. Share clear scans for an initial quote; confirm whether the authority needs original pages, stamps or a particular language pair.',
    metrics: [{ value: 'Arabic ↔ English', label: 'most-requested language pair' }, { value: 'Certified', label: 'MOJ translator route for official use' }, { value: 'Quote first', label: 'page count and language set the estimate' }],
    tags: [{ title: 'Supported language pairs', values: ['Arabic', 'English', 'French', 'Russian', 'Urdu', 'Hindi', 'German', 'Spanish', 'Chinese', 'Turkish'] }],
    highlights: [
      { title: 'Court & legal', description: 'Powers of attorney, court judgments, pleadings, contracts, affidavits and wills.' },
      { title: 'Personal records', description: 'Marriage and birth certificates, academic records, passports, licences and family documents.' },
      { title: 'Commercial', description: 'Trade licences, memoranda, tenders, agreements, corporate resolutions and banking documents.' },
    ],
    processTitle: 'From clear scan to certified copy',
    process: [
      { title: 'Upload a scan for review', detail: 'Provide every page, stamp and reverse side. Flag handwritten sections or low-resolution images.' },
      { title: 'Confirm use and language', detail: 'Identify the receiving authority, language pair, certification type, turnaround and any original-copy needs.' },
      { title: 'Translate and review', detail: 'The legal translator prepares the text and checks names, dates, figures and official terminology.' },
      { title: 'Certify and deliver', detail: 'Receive the translated document in the agreed format and confirm any attestation requirement with the receiving office.' },
    ],
    documentsTitle: 'Files to include in a quote request',
    documents: ['Legible full scan or PDF, including stamps, signatures and blank pages with endorsements', 'Source and target language', 'Country / UAE authority where the translation will be submitted', 'Required completion date and number of physical certified copies', 'Reference spelling of names from passport or Emirates ID', 'Any previous translation or glossary for consistent company / legal terms'],
    faqs: [
      { question: 'What does a MOJ-certified translation mean?', answer: 'The translation is completed and certified by a translator licensed by the UAE Ministry of Justice for the relevant language pair.' },
      { question: 'Which languages can you support?', answer: 'Arabic and English are common; French, Russian, Urdu, Hindi and other language pairs may be available depending on the licensed translator.' },
      { question: 'Can I get a quote before uploading the original?', answer: 'Yes. A clear scan is usually enough for an initial page-count and language quote. Attach the original in the secure channel requested for the final order.' },
      { question: 'Will every authority accept the same translation?', answer: 'Not always. The receiving court, notary or government department determines certification and attestation requirements.' },
    ],
    interaction: 'translation',
    formTitle: 'Request a certified translation quote',
    formDescription: 'Select the file above to note its type and page count; the file stays on your device until you choose to attach it in WhatsApp.',
  },
  'Power of Attorney (POA)': {
    title: 'Power of Attorney (POA)',
    eyebrow: 'UAE legal representation',
    description: 'Prepare a lawyer-reviewed power of attorney for the authority you intend to delegate, with drafting, translation and notarization support in one guided service.',
    heroMetric: 'DRAFT → NOTARY',
    heroLabel: 'a guided POA preparation journey',
    introTitle: 'Make the delegated authority precise and usable',
    intro: 'A power of attorney authorizes an appointed agent to act for you within stated limits. Start by describing the transaction and the receiving authority: broad general wording may be unsuitable for a specific property, vehicle or company matter. The notary and organization receiving the POA confirm the wording, identity checks and execution method they will accept.',
    metrics: [{ value: '5 POA types', label: 'general, personal, property, corporate and vehicle' }, { value: 'Online support', label: 'remote notarization depends on applicant and document eligibility' }, { value: 'Itemized quote', label: 'drafting, translation and notary charges scoped separately' }],
    highlights: [
      { title: 'General & personal', description: 'Set defined authority for personal administration, family matters or representation, with clear limits and duration.' },
      { title: 'Property & vehicle', description: 'Identify the asset and transaction, such as a sale, purchase, management task or vehicle registration action.' },
      { title: 'Corporate', description: 'Specify company representation and the permitted signing, licensing, banking or operational actions.' },
    ],
    processTitle: 'From first consultation to notarized POA',
    process: [
      { title: 'Personalized quote and scope', detail: 'Confirm the POA type, principal and agent, intended use, powers, exclusions, duration, language and signing preference.' },
      { title: 'Drafting and client review', detail: 'Prepare the draft for review. Check every name, ID detail, asset reference and authority before approving the final wording.' },
      { title: 'Translation and notarization', detail: 'Arrange the required legal translation and coordinate an eligible remote video or in-person notary appointment.' },
      { title: 'Executed document and next steps', detail: 'Receive the completed document and confirm any further attestation or original-document requirements with the organization receiving it.' },
    ],
    documentsTitle: 'POA preparation checklist',
    documents: ['Passport and Emirates ID / UAE residence copy for the principal', 'Passport and contact details for the appointed agent', 'Exact powers, limits, duration and whether substitution is allowed', 'Title deed, vehicle registration or company licence for asset-specific POAs', 'Company authorization / board resolution if a corporate principal is involved', 'Intended use and country of use to confirm notarization and attestation steps'],
    table: {
      title: 'POA pricing components',
      caption: 'A written quote is provided after confirming type, language, signing method and urgency. Official notary charges can change.',
      columns: ['Component', 'What is included', 'Pricing basis'],
      rows: [
        ['Consultation & drafting', 'Scope review and lawyer-prepared draft', 'Document complexity and number of principals'],
        ['Legal translation', 'Certified Arabic / English or other available pair', 'Language pair and page count'],
        ['Notarization', 'Appointment preparation and execution coordination', 'Notary channel, number of signers and service speed'],
        ['Attestation / courier', 'Additional legalization or delivery, if needed', 'Destination and delivery options'],
      ],
    },
    faqs: [
      { question: 'Can I prepare a power of attorney without visiting a notary office?', answer: 'Some eligible applicants and POA types can use remote video notarization. The notary must confirm identity, jurisdiction and document requirements; an office appointment may still be necessary.' },
      { question: 'Do I need to be a UAE resident to make a POA?', answer: 'Residency is not the only factor. The signing location, applicant identity, notary process and intended use determine the available route. Share the country where you will sign so the execution steps can be checked.' },
      { question: 'Can a POA be drafted in English only?', answer: 'The language accepted depends on the notary and receiving organization. UAE use may require a certified Arabic translation or bilingual format; confirm before approving the final draft.' },
      { question: 'Can a POA authorize someone to sell my Dubai property?', answer: 'A property POA can be prepared for a defined transaction, but the asset details and exact powers must meet the requirements of the notary and relevant property authority. Confirm acceptance before signing.' },
      { question: 'Should I choose a general or specific POA?', answer: 'Use only the authority needed. Property, company and vehicle transactions often need specific wording that the receiving institution accepts.' },
      { question: 'How long does a POA take?', answer: 'Timing depends on drafting approval, translation, identity checks and notary availability. A complete draft and ID set can reduce avoidable revisions.' },
      { question: 'Can I use a UAE POA abroad?', answer: 'The receiving country may require additional attestations or a different execution format. Confirm with the recipient before notarization.' },
    ],
    interaction: 'poa',
    formTitle: 'Book an online POA consultation',
    formDescription: 'Select a POA type, then share its intended use and preferred language. Do not send original identity documents through this form.',
  },
  'Wills & Last Testament': {
    title: 'Wills & Last Testament',
    eyebrow: 'UAE wills and estate planning',
    description: 'Explore Dubai Courts and DIFC will-registration routes, plan for guardianship and asset distribution, and prepare the information a qualified advisor needs to review your wishes.',
    heroMetric: 'PLAN WITH CLARITY',
    heroLabel: 'family wishes, guardianship and assets',
    introTitle: 'A considered will puts important decisions in writing',
    intro: 'A will sets out instructions for how an estate should be administered after death. Depending on the registration route and the applicable law, it may record beneficiaries, executors, guardianship wishes for eligible minor children, and instructions for property or other assets. A registered document is not a substitute for tailored legal advice: eligibility, scope, execution, and recognition depend on the testator, assets, family circumstances, and registry rules.',
    notice: {
      title: 'Choose the registration route before drafting',
      text: 'DIFC Wills Service and Dubai Courts follow different registration frameworks, document rules, language and appointment requirements. Confirm eligibility and the intended asset scope with a UAE-qualified wills advisor before signing.',
      tone: 'info',
    },
    metrics: [{ value: 'DIFC / Dubai Courts', label: 'compare registration route, eligibility and scope' }, { value: 'Guardianship wishes', label: 'subject to registry requirements and legal review' }, { value: 'Family + assets', label: 'map people, ownership and jurisdictions' }],
    highlights: [
      { title: 'Guardianship for minor children', description: 'Record proposed guardian arrangements and temporary-care wishes where the chosen route permits them. Confirm who is eligible and how the appointment takes effect.' },
      { title: 'UAE and international assets', description: 'Build an asset schedule for property, accounts, investments and business interests, noting ownership and the country where each asset is held.' },
      { title: 'Executors and beneficiaries', description: 'Identify the people who will administer the estate and those who may benefit, with clear, consistent instructions for legal review.' },
      { title: 'Property and real estate', description: 'Collect title details, ownership shares and mortgage information; verify how the selected registry can address each property.' },
      { title: 'Business and financial interests', description: 'Flag company shares, partnership interests, bank accounts, policies and investments so the advisor can assess the correct wording and supporting evidence.' },
      { title: 'Review after life changes', description: 'Revisit the document after a marriage, separation, birth, relocation, new asset or change to an executor or guardian.' },
    ],
    processTitle: 'From first consultation to will registration',
    process: [
      { title: 'Discuss family and intended outcomes', detail: 'Outline your family structure, dependents, citizenship and residence, and the decisions you want the will to cover.' },
      { title: 'Create an asset and liability map', detail: 'List major assets, ownership shares, business interests and any relevant liabilities, with the jurisdiction for each.' },
      { title: 'Compare the registry routes', detail: 'Review DIFC and Dubai Courts eligibility, available will types, language, execution method, scope and current fees with qualified counsel.' },
      { title: 'Prepare the draft', detail: 'Set out proposed executors, beneficiaries, guardianship wishes and asset instructions in route-appropriate wording.' },
      { title: 'Review and confirm details', detail: 'Check legal names, identity documents, asset identifiers, appointments and any translation or witness requirements before signing.' },
      { title: 'Execute, register and store', detail: 'Complete the required signing and registration steps, retain the registered copy and note when the document should be reviewed.' },
    ],
    documentsTitle: 'Will consultation and registration checklist',
    documents: [
      'Testator passport, Emirates ID, UAE visa / residence details and contact information',
      'Full legal names and identity details of spouse, children, beneficiaries, proposed executors and guardians',
      'Marriage, divorce, birth or other family records relevant to the proposed instructions',
      'UAE property title deeds, plot or unit references, ownership shares and mortgage details',
      'Summary of UAE and overseas bank accounts, investments, insurance and other financial interests; do not send account credentials',
      'Company names, licence details, shareholding or partnership records for business assets',
      'Country and location for each material asset, including any assets outside the UAE',
      'Existing wills, codicils, court orders, trusts or prior estate-planning documents',
      'Preferred registration route, language, appointment constraints and any proposed witnesses',
    ],
    table: {
      title: 'DIFC Wills Service and Dubai Courts: route comparison',
      caption: 'A planning comparison only, not a statement that either route is suitable for every person or asset. Availability and rules can change; confirm the current registry requirements and obtain legal advice.',
      columns: ['Planning factor', 'DIFC Wills Service', 'Dubai Courts'],
      rows: [
        ['Registration framework', 'DIFC Wills Service rules and registration process', 'Dubai Courts registration and execution process'],
        ['Eligibility', 'Check current testator eligibility and the conditions for the chosen will type', 'Confirm eligibility and the will type accepted for the testator’s circumstances'],
        ['Language and execution', 'Language, remote / in-person execution and witness rules depend on the current service option', 'Arabic drafting or certified translation and court appointment formalities may be required'],
        ['Will types and instructions', 'Available options may cover different combinations of property, financial assets and guardianship', 'Available forms and permitted provisions depend on current court services and legal review'],
        ['Asset scope', 'Confirm whether each UAE or non-UAE asset is covered by the selected registration option', 'Confirm asset coverage and the legal effect for each relevant jurisdiction'],
        ['Fees and appointment', 'Registry charges and appointment availability depend on will type and current tariff', 'Court and related professional charges depend on route and current fee schedule'],
        ['Best next step', 'Request an eligibility and asset-scope review before drafting', 'Confirm language, supporting records and execution steps before booking'],
      ],
    },
    benefits: [
      { title: 'Family instructions', description: 'Bring key wishes for dependents, executors and estate administration into a document prepared for formal registration.' },
      { title: 'Guardianship planning', description: 'Discuss proposed care arrangements for minor children and confirm how the relevant registry treats those instructions.' },
      { title: 'Asset visibility', description: 'Organize property, financial and business records across the jurisdictions where assets are located.' },
      { title: 'A reviewable record', description: 'Keep a registered document that can be reviewed when family circumstances, assets or legal requirements change.' },
    ],
    faqs: [
      { question: 'What does a will do?', answer: 'A will records instructions for estate administration and distribution after death, subject to its terms, the applicable law and recognition by the relevant authority.' },
      { question: 'Who should consider making a UAE will?', answer: 'People with dependents, UAE property, financial interests, business assets or specific estate instructions may wish to discuss a will with qualified counsel.' },
      { question: 'Can a will name guardians for children?', answer: 'A route may allow guardianship wishes for eligible minor children. The registry’s rules, guardian eligibility and legal effect must be checked for the family’s circumstances.' },
      { question: 'Should I choose DIFC or Dubai Courts?', answer: 'There is no universal best option. Compare eligibility, available will types, language, asset scope, execution method and current fees with a UAE-qualified advisor.' },
      { question: 'Can one UAE will cover property outside the UAE?', answer: 'Cross-border recognition and asset coverage vary. List the jurisdiction of each overseas asset and obtain advice on whether a separate local document is needed.' },
      { question: 'Do I need to list every bank account in the will?', answer: 'The correct level of detail depends on the will type and legal advice. Prepare a private asset inventory for your advisor, but never share login credentials or full account access details.' },
      { question: 'How long does registration take and what does it cost?', answer: 'Timing, appointments and charges vary by registry, will type, drafting complexity and current service capacity. Request an itemized quote and timeline before proceeding.' },
      { question: 'When should an existing will be reviewed?', answer: 'Review it after a marriage, divorce, birth, relocation, major purchase or sale, change in business interests, or a change to a named executor or guardian.' },
    ],
    formTitle: 'Book a will-planning consultation',
    formDescription: 'Tell us which registration route you are considering and whether you need help with guardianship, UAE property, financial assets or business interests. Do not submit account numbers, passwords or confidential asset statements.',
  },
  'DLD Trustee Services': {
    title: 'DLD Trustee Services',
    eyebrow: 'Dubai property transactions',
    description: 'Coordinate a Dubai property sale transfer, title deed update, gift, mortgage registration or release with a transaction-specific DLD trustee document and payment checklist.',
    heroMetric: 'DLD TRUSTEE',
    heroLabel: 'transfer, mortgage and ownership records',
    introTitle: 'Prepare each party and approval before the trustee appointment',
    intro: 'A trustee transaction can involve the buyer, seller, developer, lender, representative and Dubai Land Department. Requirements change with property status and transaction type. Confirm the title details, outstanding charges, NOC, bank instructions, signatory authority and payment method with the selected trustee office before attending.',
    notice: {
      title: 'Confirm the live transaction total before arranging payment',
      text: 'DLD registration, trustee, developer, bank, valuation and other charges depend on the transaction and can change. The fee guide below is not a payment quote; request a current written breakdown for the exact property and transaction.',
      tone: 'warning',
    },
    metrics: [{ value: 'Buyer + seller', label: 'verify IDs, names, authority and attendance' }, { value: 'NOC + bank', label: 'clearance or lender documents may be required' }, { value: 'Transaction-specific', label: 'confirm DLD and trustee charges in advance' }],
    highlights: [
      { title: 'Property sale and ownership transfer', description: 'Prepare buyer and seller identification, title and sale records, developer clearance and payment arrangements for the trustee review.' },
      { title: 'Title deed and ownership record', description: 'Check that names, unit details and ownership shares match the official records, and prepare evidence for a correction or title service request.' },
      { title: 'Family gift transfer', description: 'Review relationship evidence, property valuation and the recipient’s details; confirm eligibility, fees and supporting records for the intended transfer.' },
      { title: 'Mortgage registration', description: 'Coordinate lender approval, finance documents and the registration requirements for a property being mortgaged.' },
      { title: 'Mortgage release or transfer', description: 'Obtain the bank’s settlement or liability statement and release instructions, then confirm the sequence with the lender and trustee.' },
      { title: 'Developer NOC and clearance', description: 'Track the developer’s NOC and outstanding service-charge clearance where required before completing the registration.' },
    ],
    processTitle: 'Dubai Land Department trustee registration workflow',
    process: [
      { title: 'Identify the transaction route', detail: 'Confirm whether the request is a sale, gift, mortgage registration, mortgage release, ownership update or title deed service.' },
      { title: 'Verify property and party records', detail: 'Match the title deed, unit details, buyer and seller names, ownership shares and authorized signatories before booking.' },
      { title: 'Clear developer and lender conditions', detail: 'Request the developer NOC and service-charge clearance where needed; obtain bank liability, settlement and release documents for a financed property.' },
      { title: 'Prepare payment and appointment evidence', detail: 'Ask the trustee for its current document list, accepted payment instruments, fee breakdown, booking requirements and attendance rules.' },
      { title: 'Submit the file for trustee review', detail: 'The parties or valid representatives present the required identity and transaction documents for review and DLD processing.' },
      { title: 'Complete registration and retain records', detail: 'Settle the confirmed charges, complete the transaction and verify the updated title deed or registration record after issuance.' },
    ],
    documentsTitle: 'DLD trustee appointment document checklist',
    documents: [
      'Original Emirates IDs and passport copies for each buyer, seller, recipient or authorized signatory',
      'Current title deed, unit or plot reference and signed sale / transfer agreement where applicable',
      'Developer NOC and service-charge clearance for transactions that require them',
      'Bank liability letter, settlement confirmation and mortgage release / registration instructions where applicable',
      'Valid POA covering the specific transaction, plus identity documents for the principal and representative',
      'Company trade licence, authorized signatory evidence and corporate resolution for entity-owned property',
      'Relationship evidence and valuation records for a family gift or other qualifying transfer route',
      'Buyer and seller contact details, appointment confirmation and any required application reference',
      'Manager’s cheque, bank payment proof or other payment method confirmed with the trustee in advance',
      'Any additional DLD, lender, developer or trustee forms requested for the property and transaction type',
    ],
    table: {
      title: 'Trustee transaction fees and payment items',
      caption: 'This list explains common charge categories; it does not set current rates. Ask the trustee, DLD, developer and lender for a written amount based on the exact transaction before arranging funds.',
      columns: ['Cost item', 'When it may apply', 'What to verify'],
      rows: [
        ['DLD sale registration', 'May be calculated by transaction category and registered sale value', 'Current tariff, any applicable exception and the buyer / seller allocation in the contract'],
        ['Trustee office service', 'May be charged for file handling and registration support', 'Current centre charge, VAT and any additional service item'],
        ['Developer NOC / clearance', 'May apply to a sale, transfer or ownership update', 'Developer charge, outstanding service fees and NOC validity period'],
        ['Mortgage registration', 'Applies when registering lender security against a property', 'DLD and bank requirements, finance documents and current charge basis'],
        ['Mortgage release / settlement', 'Applies when a loan is paid, cleared or transferred', 'Bank settlement figure, release charge and discharge sequence'],
        ['Gift or family transfer', 'Depends on relationship, property and accepted transfer route', 'Eligibility evidence, valuation basis and applicable registration fees'],
        ['Other transaction expenses', 'May include valuation, translation, POA, courier or document services', 'Which items are mandatory, optional and billed by each provider'],
      ],
    },
    faqs: [
      { question: 'Which property matters can be handled through a trustee office?', answer: 'Common matters include sale transfers, mortgage registration or release, gift transfers and selected title deed or ownership-record services. Confirm that the chosen office supports the exact transaction.' },
      { question: 'Who pays the DLD transfer and trustee charges?', answer: 'The registered charges depend on the transaction. The parties may agree how some costs are allocated, but that agreement does not alter the amount collected by the authority. Obtain a current itemized breakdown before completion.' },
      { question: 'Is a developer NOC always required?', answer: 'Requirements depend on property status, developer and transaction. Ask the developer and trustee whether an NOC or service-charge clearance is needed and how long it remains valid.' },
      { question: 'What documents are needed to release a mortgage?', answer: 'The lender usually provides transaction-specific settlement and release instructions. Confirm the liability figure, payment proof, release letter and registration sequence with both the lender and trustee.' },
      { question: 'Can a POA holder attend instead of a buyer or seller?', answer: 'A representative may be accepted when the POA grants the necessary powers and meets current execution, attestation and language rules. The trustee must approve it for the specific transaction.' },
      { question: 'Must both buyer and seller attend?', answer: 'Attendance rules depend on the transaction, identity verification and whether a valid representative is accepted. Confirm the appointment conditions with the selected trustee office.' },
      { question: 'Can I get a final fee total from this page?', answer: 'No. DLD, trustee, developer and bank charges depend on the property and case. Request the current amounts directly and have each item identified before arranging payment.' },
      { question: 'When is the new title deed available?', answer: 'Timing depends on document completeness, payment clearance and DLD processing. Confirm the expected issuance channel and follow-up method at the appointment.' },
    ],
    formTitle: 'Request a DLD trustee file review',
    formDescription: 'Tell us the transaction type, property status, whether a lender is involved and which documents you already have. Do not send bank login information or original identity documents in an initial enquiry.',
  },
  'Property Revaluation': {
    title: 'Property Revaluation',
    eyebrow: 'Dubai Land Department valuation',
    description: 'Understand the official property valuation process and prepare the property records needed for residence eligibility, gifting, finance, court or ownership matters.',
    heroMetric: 'DLD VALUATION',
    heroLabel: 'official assessment for property records',
    introTitle: 'One official assessment can support several property decisions',
    intro: 'A Dubai Land Department valuation records an authority-assessed value for the property and purpose stated in the application. Owners may need it for immigration eligibility checks, family transfers, lending, court matters or financial reporting. The resulting figure is determined by the authority and is not guaranteed to match a requested amount, previous estimate or asking price. Confirm the certificate’s validity and acceptance with the organization that will receive it.',
    notice: {
      title: 'A valuation result is determined by DLD',
      text: 'A preliminary market review is not an official certificate and cannot promise a target value. Confirm the current DLD service, supporting evidence, charges and receiving-authority requirements before applying.',
      tone: 'info',
    },
    metrics: [{ value: 'Purpose-led', label: 'identify the receiving authority and certificate use' }, { value: 'Property records', label: 'title, unit and ownership details must match' }, { value: 'DLD decision', label: 'final value and issuance remain with the authority' }],
    highlights: [
      { title: 'Residence eligibility review', description: 'An official valuation may help establish current property value when reviewing a Golden Visa or retirement-residence route. Immigration authorities decide whether the evidence meets their criteria.' },
      { title: 'Family gift transfer', description: 'Where a property is gifted to an eligible relative, the relevant DLD transfer route may require a valuation to determine the applicable registration basis.' },
      { title: 'Mortgage and refinancing', description: 'A lender may request a current valuation when reviewing a new facility, refinancing, loan-to-value or revised mortgage terms.' },
      { title: 'Inheritance and court matters', description: 'A formal property value may be requested for estate administration, dispute resolution, court submissions or division of real-estate interests.' },
      { title: 'Company and financial review', description: 'Organizations may need property evidence for internal asset records, accounting, audit or tax-related review. Confirm the appropriate valuation purpose with the requesting professional.' },
      { title: 'Sale and ownership transfer', description: 'A valuation can support transaction planning or may be requested to establish a property value for a DLD process. It does not replace a sale agreement or confirm the final transaction price.' },
    ],
    processTitle: 'From property audit to DLD certificate',
    process: [
      { title: 'Define the receiving purpose', detail: 'Tell the advisor whether the valuation is for residency, family gifting, finance, sale, court or company records, and identify who will use the certificate.' },
      { title: 'Review the property evidence', detail: 'Match the title deed, owner identity, plot or unit details and ownership share. Gather floor plans, photographs, mortgage records or other evidence requested for the property.' },
      { title: 'Prepare the application', detail: 'Confirm the available DLD service, current charges and submission route, then provide the required records and arrange access or inspection if the authority requests it.' },
      { title: 'DLD assessment', detail: 'The authority reviews the application and available property and market information. Additional evidence or clarification may be requested before a decision.' },
      { title: 'Check the issued certificate', detail: 'Verify owner, property, purpose and valuation details, then confirm that the receiving bank, court or immigration authority accepts this certificate and date.' },
    ],
    documentsTitle: 'Property valuation application checklist',
    documents: [
      'Current DLD title deed or ownership record with plot, building and unit identifiers',
      'Owner passport, Emirates ID, contact details and any required authorization for a representative',
      'Property type, location, area, configuration, current use and ownership share',
      'Floor plan, recent property photographs or inspection access details if requested',
      'Mortgage statement, lender request or finance reference for a refinancing case',
      'Purpose letter or requirements supplied by the bank, immigration authority, court or company',
      'Prior valuation reports, relevant transaction records or supporting property evidence',
      'For gifting: relationship documents and details of the proposed transfer route',
      'For corporate or court use: company instruction, case reference or other recipient-specific request',
      'Payment confirmation for the current government service fee, once verified through the official channel',
    ],
    table: {
      title: 'Prepare according to the valuation purpose',
      caption: 'The receiving organization determines what it will accept. These examples are preparation guidance, not a guarantee that a particular certificate will meet an external requirement.',
      columns: ['Purpose', 'What to clarify first', 'Common supporting records'],
      rows: [
        ['Golden Visa or retirement review', 'Current eligibility threshold and whether the receiving authority accepts a DLD valuation for this property', 'Title deed, owner identity, ownership share and any immigration checklist'],
        ['Family gifting', 'Eligible relationship, accepted gift-transfer route and valuation basis for the transaction', 'Title deed, owner and recipient identity, relationship proof and transfer request'],
        ['Mortgage or refinancing', 'Lender valuation format, inspection requirements, validity period and who may submit the request', 'Title deed, property details, lender request and current mortgage information'],
        ['Inheritance or court matter', 'Court instructions, required valuation date and report format', 'Title deed, case reference, ownership evidence and representative authorization'],
        ['Company or financial reporting', 'Reporting standard, valuation date, intended audience and accounting advice', 'Company instruction, title, property records and prior audit / valuation material'],
        ['Sale or ownership transfer', 'Whether a valuation is required and how the receiving DLD process uses it', 'Title deed, transaction details, buyer / seller or transfer-party records'],
      ],
    },
    faqs: [
      { question: 'What is a DLD property valuation certificate?', answer: 'It is an official valuation outcome issued through the relevant Dubai Land Department service. The valuation is based on the application, property information and the authority’s assessment.' },
      { question: 'Can a valuation help me qualify for a Golden Visa?', answer: 'It may provide property-value evidence for an eligibility review. The immigration authority decides whether the property, ownership and certificate satisfy the current visa criteria.' },
      { question: 'Does the valuation guarantee a particular property value?', answer: 'No. The authority determines the result. A prior purchase price, market estimate or requested amount does not guarantee the certificate value.' },
      { question: 'Is a DLD valuation required for family gifting?', answer: 'A valuation may be required for some gift-transfer procedures or to determine the transaction basis. Verify the relationship rules and current document list for your case.' },
      { question: 'Will DLD inspect the property?', answer: 'The authority may request access, photographs, a floor plan or additional information depending on the property and application. Follow the instructions given for the specific service.' },
      { question: 'Can I use one certificate for a bank and an immigration application?', answer: 'Do not assume it will be accepted for both. Ask each receiving organization about purpose, format, issue date, validity and required ownership evidence.' },
      { question: 'How long is a property valuation certificate valid?', answer: 'Validity and acceptance periods depend on the service and receiving organization. Confirm the current certificate date requirements before submission.' },
      { question: 'How much does an official valuation cost?', answer: 'The current charge depends on the DLD service and application details. Verify the government fee through the official channel before payment; any professional support should be itemized separately.' },
      { question: 'How long does the valuation process take?', answer: 'Processing depends on document completeness, property review and whether further information or inspection is requested. Confirm the current service estimate when submitting.' },
    ],
    formTitle: 'Request a DLD valuation file review',
    formDescription: 'Tell us the property type, Dubai area and intended use—residence eligibility, gifting, finance, court, company review or transfer. Do not send bank passwords or confidential account credentials.',
  },
  'Medical & EID': {
    title: 'Medical Fitness & EID Locations',
    eyebrow: 'Medical fitness and biometrics',
    description: 'Find DHA medical fitness and ICP Emirates ID biometric centres in Dubai, compare express options and arrive prepared.',
    heroMetric: 'DHA + ICP',
    heroLabel: 'medical fitness and identity appointments',
    introTitle: 'Choose the right centre for each required appointment',
    intro: 'Residence applicants may need a DHA medical fitness test and a separate ICP Emirates ID biometric appointment. VIP or express services may be available at selected facilities for an extra fee; they do not change medical eligibility or guarantee visa approval.',
    notice: {
      title: 'Medical and biometrics are separate appointments',
      text: 'Follow the centre and time printed on each confirmation. The medical result and Emirates ID biometrics may be handled by different providers, so check both bookings before travelling.',
      tone: 'info',
    },
    metrics: [{ value: 'Blood test', label: 'screening required for adult applicants' }, { value: 'Chest X-ray', label: 'may be part of medical fitness screening' }, { value: 'Two authorities', label: 'DHA medical and ICP biometrics are separate steps' }],
    highlights: [
      { title: 'VIP / express screening', description: 'Selected medical fitness centres offer paid priority options. Confirm availability, fee and reporting time before booking.' },
      { title: 'Medical fitness', description: 'Bring the passport, application / UID details and appointment confirmation; follow facility instructions for the required test.' },
      { title: 'Emirates ID biometrics', description: 'Attend the ICP-designated centre with the original passport and appointment notice; children may have different requirements.' },
    ],
    processTitle: 'Appointment-day preparation',
    process: [
      { title: 'Check your medical application', detail: 'Confirm the DHA centre, service speed, appointment time and documents on the medical fitness application.' },
      { title: 'Complete blood test and X-ray', detail: 'Follow the centre’s fasting, medication and health instructions; ask the clinic in advance if you have a medical concern.' },
      { title: 'Book / attend ICP biometrics', detail: 'Use the ICP appointment notice and take the original passport for fingerprints and photograph if requested.' },
      { title: 'Track results and ID', detail: 'Use the application references to follow medical results and Emirates ID status with the respective authorities.' },
    ],
    documentsTitle: 'What to carry',
    documents: ['Original passport and valid UAE entry permit / residence file', 'Medical fitness application or UID / unified number', 'Emirates ID application reference and ICP appointment confirmation', 'Recent passport-size photograph if requested by the facility', 'Glasses / contact lens details or medical records if relevant to the test', 'Payment method for centre charges and any optional express service'],
    faqs: [
      { question: 'Can I choose any medical centre?', answer: 'Use a DHA-approved medical fitness centre that supports your selected service. Verify current availability and the correct application before travelling.' },
      { question: 'Do I need to fast before a medical fitness test?', answer: 'Follow the instructions on your appointment or ask the medical centre. Do not fast unless the facility specifically directs you to.' },
      { question: 'Can express screening guarantee the result sooner?', answer: 'Priority service may reduce waiting time at the centre but does not guarantee laboratory reporting or immigration approval timing.' },
      { question: 'Are the medical and ID biometrics at the same location?', answer: 'They are separate authority steps and may be at different locations. Check each appointment confirmation carefully.' },
    ],
    interaction: 'locations',
    formTitle: 'Find the right appointment location',
    formDescription: 'Tell us which step you need—DHA medical fitness or ICP biometrics—and your Dubai area.',
  },
  'Visa Validity Checker': {
    title: 'Visa Validity Checker',
    eyebrow: 'Check official immigration status',
    description: 'Use the correct ICP or GDRFA portal to verify a visa, understand where to find the reference number and estimate overstay exposure.',
    heroMetric: 'CHECK OFFICIAL',
    heroLabel: 'ICP and GDRFA government channels',
    introTitle: 'Always verify status with the authority that issued the visa',
    intro: 'Use ICP for federal immigration files and GDRFA for Dubai-issued files. Third-party guidance cannot confirm a live government record. Have the passport and visa or application details ready, and verify grace-period dates directly before booking travel.',
    notice: {
      title: 'This page does not retrieve private immigration records',
      text: 'For a live result, use the official ICP or GDRFA service. Grace periods and fines depend on visa category and current records; do not rely on an estimate for travel or payment decisions.',
      tone: 'warning',
    },
    metrics: [{ value: 'ICP', label: 'federal emirates and file status' }, { value: 'GDRFA Dubai', label: 'Dubai-issued residence and entry permits' }, { value: 'AED 50/day', label: 'commonly cited overstay fine after grace; verify live amount' }],
    highlights: [
      { title: 'ICP status', description: 'Use the ICP Smart Services portal for visa validity and application information for federal files.' },
      { title: 'GDRFA Dubai status', description: 'Dubai visa holders should use GDRFA Dubai’s official website or app for their file and fine information.' },
      { title: 'Overstay prevention', description: 'Grace periods differ by visa and cancellation reason. Confirm the final permitted date on the official record before travel.' },
    ],
    processTitle: 'How to check your UAE visa online',
    process: [
      { title: 'Identify the issuing emirate', detail: 'A Dubai-issued visa is generally checked through GDRFA Dubai. For Abu Dhabi and the other emirates, start with the federal ICP service.' },
      { title: 'Open the official authority portal', detail: 'Use the government links on this page and select the service for visa or file validity.' },
      { title: 'Choose an available search method', detail: 'The portal may offer a passport-information search or a file / application reference search; use only the options currently shown.' },
      { title: 'Enter details on the government site', detail: 'Provide the requested passport or file information only on the official portal. Never give another party your UAE Pass password or one-time code.' },
      { title: 'Review validity and status', detail: 'Check the displayed visa status and dates against your visa and travel records. Save the result or its reference for follow-up.' },
      { title: 'Confirm grace dates and any fine', detail: 'Use the authority record to confirm the last permitted stay and exact amount due. Contact the authority if records conflict or a fine appears incorrect.' },
    ],
    documentsTitle: 'Have these details ready',
    documents: ['Passport number, nationality and passport expiry date', 'Visa copy or application / file number if available', 'Unified number (UID) where requested by the official service', 'Emirate / issuing authority and visa type', 'Cancellation date and exit record for a cancelled residence visa', 'Official result reference and payment receipt if a fine is displayed'],
    faqs: [
      { question: 'Which site should I use for a Dubai visa?', answer: 'Use GDRFA Dubai’s official service channels for a visa issued by Dubai. Use ICP for federal files and visas issued by other emirates.' },
      { question: 'Can I check a visa using only a passport number?', answer: 'The official portal may request nationality, date of birth, passport expiry or other matching data. Follow the fields presented by the government service.' },
      { question: 'How much is the overstay fine?', answer: 'A commonly cited rate is AED 50 per day after the applicable grace period, but rates and grace periods can change by visa category. Confirm the exact live amount with the issuing authority.' },
      { question: 'Does this page access government records?', answer: 'No. The guide and fine estimator do not connect to immigration databases or send passport details. Use ICP or GDRFA for the live file result.' },
    ],
    interaction: 'visa-checker',
    formTitle: 'Need help understanding an official result?',
    formDescription: 'Share the issuing emirate, visa type and the wording of the notice. Never send passwords, OTPs or full passport images in an initial inquiry.',
  },
  'ILOE Insurance': {
    title: 'ILOE Insurance',
    eyebrow: 'UAE unemployment insurance',
    description: 'Understand mandatory ILOE cover, compare salary-based premiums, estimate a possible claim benefit and learn how to check your policy and fines securely.',
    heroMetric: '60%',
    heroLabel: 'of average basic salary, subject to category caps and eligibility',
    introTitle: 'Know your cover before you need to claim',
    intro: 'Involuntary Loss of Employment (ILOE) insurance provides a temporary benefit after qualifying involuntary job loss. Most private-sector and federal-government employees are required to subscribe, while specified groups are exempt. Keep premiums current and verify your live status directly with the official ILOE service.',
    metrics: [{ value: 'AED 5/mo', label: 'Category A: basic salary up to AED 16,000' }, { value: 'AED 10/mo', label: 'Category B: basic salary above AED 16,000' }, { value: 'AED 400 + 200', label: 'subscription and late-premium fines, where applicable' }],
    highlights: [
      { title: 'Category 1 / A', description: 'Basic salary up to AED 16,000: premium is AED 5 per month plus VAT; annual, quarterly and monthly payment options may be offered.' },
      { title: 'Category 2 / B', description: 'Basic salary above AED 16,000: premium is AED 10 per month plus VAT; confirm the current plan and payment channel.' },
      { title: 'Claim requirements', description: 'Common guidance includes 12 consecutive months of subscription, qualifying involuntary job loss and submitting a claim within 30 days.' },
      { title: 'Status and penalty checks', description: 'Review your own policy, receipts and any recorded fines on the official portal. Do not share Emirates ID details or login codes in an informal inquiry.' },
    ],
    processTitle: 'Subscribe and keep the policy active',
    process: [
      { title: 'Confirm your category', detail: 'Use your basic salary—not total package—to identify the applicable category and premium.' },
      { title: 'Subscribe through an approved channel', detail: 'Use the official ILOE website, app, exchange, kiosk or other approved channel.' },
      { title: 'Choose a payment frequency', detail: 'Monthly, quarterly or annual instalments may be available. Keep receipts and check that automatic payments do not expire or fail.' },
      { title: 'Check status and fines', detail: 'Review policy and penalty status with the official checker; resolve any recorded amount using the official payment options.' },
    ],
    documentsTitle: 'Before checking or subscribing',
    documents: ['Emirates ID and contact details for the official ILOE check', 'Basic monthly salary to identify the correct category', 'Employer and sector details to confirm mandatory status', 'Valid email and UAE mobile number for policy notices', 'Payment card or approved-channel information', 'Policy number and subscription receipts for an existing plan'],
    table: {
      title: 'ILOE plan comparison',
      caption: 'Premiums below are the commonly published base amounts and exclude VAT. Check the official insurer / ILOE portal for current pricing and eligibility.',
      columns: ['Category', 'Monthly basic salary', 'Base premium', 'Maximum monthly benefit'],
      rows: [
        ['Category A / 1', 'AED 16,000 or less', 'AED 5 + VAT', 'Up to AED 10,000 for up to 3 months'],
        ['Category B / 2', 'Above AED 16,000', 'AED 10 + VAT', 'Up to AED 20,000 for up to 3 months'],
      ],
    },
    faqs: [
      { question: 'Who is exempt from ILOE?', answer: 'Investors / business owners, domestic workers, employees under 18 and certain pensioners who take a new job are generally exempt. Verify your employment category.' },
      { question: 'What are the common fines?', answer: 'The current cited penalties are AED 400 for failing to subscribe and AED 200 for premiums unpaid for more than three months. Check the official ILOE portal for your account.' },
      { question: 'How much compensation can I receive?', answer: 'Eligible claims are generally calculated at 60% of average basic salary over the preceding six months, subject to a monthly category cap and a maximum of three months per claim.' },
      { question: 'What conditions apply to an ILOE claim?', answer: 'Commonly published guidance refers to at least 12 consecutive months of subscription, qualifying involuntary job loss and filing within 30 days of the last working day. The insurer assesses the policy and evidence.' },
      { question: 'Does resignation qualify for a claim?', answer: 'The scheme is for qualifying involuntary job loss. Resignation and dismissal for cause are generally not covered; the insurer reviews the circumstances and decides the claim.' },
      { question: 'How can I check my subscription or fine?', answer: 'Use the official ILOE portal and its identity-verification process. This page does not retrieve government or insurer account data.' },
      { question: 'Can I pay monthly or annually?', answer: 'Payment schedules can include monthly, quarterly or annual options depending on the approved channel. Check the current options and keep your payment confirmation.' },
    ],
    interaction: 'iloe',
    formTitle: 'Get help understanding ILOE requirements',
    formDescription: 'Use the official ILOE channel for live account status. For general guidance, share your employment category only—never include your Emirates ID number, password or OTP.',
  },
};
