export interface ServiceFaq {
  question: string;
  answer: string;
}

export interface ServiceStep {
  title: string;
  detail: string;
}

export interface ServiceTable {
  title: string;
  caption?: string;
  columns: string[];
  rows: string[][];
}

export interface ServiceTab {
  label: string;
  title: string;
  detail: string;
  points: string[];
}

export interface ServicePageContent {
  title: string;
  eyebrow: string;
  description: string;
  heroMetric: string;
  heroLabel: string;
  introTitle: string;
  intro: string;
  metrics: { value: string; label: string }[];
  highlights: { title: string; description: string }[];
  processTitle: string;
  process: ServiceStep[];
  documentsTitle: string;
  documents: string[];
  faqs: ServiceFaq[];
  notice?: { title: string; text: string; tone?: 'warning' | 'info' };
  table?: ServiceTable;
  benefits?: { title: string; description: string }[];
  tags?: { title: string; values: string[] }[];
  tabs?: ServiceTab[];
  interaction?: 'golden' | 'attestation' | 'visa-checker' | 'locations' | 'translation' | 'poa' | 'iloe';
  formTitle: string;
  formDescription: string;
}

export const serviceCatalog: Record<string, ServicePageContent> = {
  'Family Visa': {
    title: 'Family Visa',
    eyebrow: 'UAE family residence',
    description: 'Bring your family to the UAE with a clear, case-checked plan for sponsorship, attestation, entry permits and residence formalities.',
    heroMetric: 'AED 4,000',
    heroLabel: 'general monthly sponsor salary',
    introTitle: 'A well-prepared family file starts with the sponsor',
    intro: 'Spouse and child sponsorship usually begins with a UAE-resident sponsor, proof of the family relationship and evidence of qualifying income. Parents have higher income and accommodation requirements. Eligibility and final fees vary by emirate, relationship and current authority rules, so confirm the case before submitting.',
    metrics: [{ value: 'AED 4,000', label: 'salary, or AED 3,000 with employer housing' }, { value: '5–10 days', label: 'typical new application, after documents are ready' }, { value: '120 days', label: 'newborn residence deadline from birth' }],
    highlights: [
      { title: 'Sponsor salary', description: 'AED 4,000 monthly, or AED 3,000 where the employer provides accommodation, is the general spouse-and-child threshold.' },
      { title: 'Parents need a separate review', description: 'Parent sponsorship is commonly assessed around AED 20,000 monthly, with suitable housing, insurance and additional conditions.' },
      { title: 'Attested relationship proof', description: 'Foreign marriage and birth certificates need the required home-country and UAE attestations, followed by certified Arabic translation.' },
    ],
    processTitle: 'From entry permit to residence visa',
    process: [
      { title: 'Open or update the family file', detail: 'Check sponsor eligibility, attest relationship certificates and submit the dependent residence entry-permit application.' },
      { title: 'Enter or change status', detail: 'The dependent enters on the permit, or applies for an in-country status change when eligible.' },
      { title: 'Medical fitness & Emirates ID', detail: 'Adult dependents complete medical fitness screening and the Emirates ID application/biometrics.' },
      { title: 'Residence issuance', detail: 'After the required approvals and fees, the electronic residence permit is issued and linked to the Emirates ID.' },
    ],
    documentsTitle: 'Family sponsorship document checklist',
    documents: ['Sponsor passport, UAE residence and Emirates ID', 'Sponsor salary certificate or labour contract and accommodation proof where applicable', 'Dependent passport copy with required validity and a recent photo', 'Attested marriage certificate for a spouse or birth certificate for a child', 'Tenancy contract / Ejari and health insurance where required', 'Application number, entry permit or previous visa for an in-country status change'],
    faqs: [
      { question: 'Can a wife sponsor her husband and children?', answer: 'Yes. A UAE-resident woman can sponsor eligible family members when she meets the applicable income and occupation conditions. The authority may request additional evidence, so check the file before lodging it.' },
      { question: 'Does a family member on a visit visa need to leave the UAE?', answer: 'Often an in-country change-of-status application can be used instead of exit and re-entry. The correct route depends on the visa and current authority rules.' },
      { question: 'How much does family visa processing cost?', answer: 'Government, medical, Emirates ID, insurance and service-centre charges depend on visa duration, emirate and whether the family file is new. Ask for an itemised quote before payment.' },
      { question: 'Do foreign certificates need attestation?', answer: 'Marriage and birth records generally require the issuing-country chain of attestation, UAE Embassy attestation and UAE MOFA attestation, plus certified Arabic translation.' },
    ],
    formTitle: 'Check your family sponsorship eligibility',
    formDescription: 'Share the sponsor emirate, relationship and intended visa route for a tailored document list and itemised estimate.',
    table: {
      title: 'Family visa cost breakdown',
      caption: 'Fees vary by emirate, visa duration and whether a family file is already open. Ask for a current quote with government charges and optional services separated.',
      columns: ['Cost item', 'When it applies', 'How it is quoted'],
      rows: [
        ['Family file opening', 'First time sponsoring a dependent', 'One-time government fee'],
        ['Entry permit / status change', 'New dependent or applicant already in the UAE', 'Government fee by route'],
        ['Medical fitness & Emirates ID', 'Adult dependent applications; child steps differ', 'Government fees by age and visa duration'],
        ['Health insurance', 'Where required for the emirate and dependent category', 'Policy premium based on cover and age'],
        ['Attestation & Arabic translation', 'Foreign marriage or birth certificate', 'Quoted separately by document and country'],
        ['Typing / professional service', 'Optional application preparation and follow-up', 'Service fee shown separately from government costs'],
      ],
    },
  },
  'Golden Visa': {
    title: 'Golden Visa',
    eyebrow: 'Long-term UAE residency',
    description: 'Explore the right 10-year residency route, compare category requirements and prepare the evidence before starting a nomination or application.',
    heroMetric: '10 YEARS',
    heroLabel: 'long-term residency route',
    introTitle: 'Start with the strongest qualifying category',
    intro: 'Golden Visa eligibility is category-specific. Dubai real-estate investors, skilled professionals, entrepreneurs and high-achieving students rely on different evidence and approval channels. Use the guide below to narrow your route, then confirm current criteria with the relevant authority before making financial decisions.',
    metrics: [{ value: 'AED 2M+', label: 'qualifying Dubai property value route' }, { value: '10 years', label: 'residence validity, subject to category approval' }, { value: 'Family', label: 'eligible dependents can be sponsored' }],
    highlights: [
      { title: 'Route-first advice', description: 'A category review checks whether property, professional, entrepreneur or student evidence is the best fit.' },
      { title: 'Application sequencing', description: 'Coordinate nomination, document attestation, medical fitness and Emirates ID without cancelling existing status prematurely.' },
      { title: 'Family planning', description: 'Plan eligible spouse, children and other dependents alongside the main applicant file.' },
    ],
    processTitle: 'A considered route from eligibility to residency',
    process: [
      { title: 'Eligibility screener', detail: 'Select the closest route and provide the relevant profile details to prepare for an advisor review.' },
      { title: 'Evidence and nomination', detail: 'Collect category-specific proof and submit the nomination or initial application through the correct authority channel.' },
      { title: 'Medical and biometrics', detail: 'After the required approval, complete medical fitness and Emirates ID formalities in the UAE.' },
      { title: 'Residence issuance', detail: 'Complete the final authority steps and coordinate eligible family applications.' },
    ],
    documentsTitle: 'Core documents to prepare',
    documents: ['Passport and current UAE visa / Emirates ID if resident', 'Recent photograph and contact details', 'Property title deed and DLD valuation, or salary / employment evidence, as relevant', 'Attested degree and professional licence for applicable skilled-professional routes', 'Company licence, ownership or investment records for entrepreneur routes', 'Student transcripts, graduation evidence and recommendation where applicable'],
    faqs: [
      { question: 'Does a mortgaged property count toward AED 2 million?', answer: 'The property value is generally assessed rather than only the applicant’s equity. A current DLD valuation may help when the historical title-deed value is outdated; confirm the individual file.' },
      { question: 'Does a salary package above AED 30,000 qualify?', answer: 'For the salaried professional route, the basic salary on the labour contract may be assessed, along with occupation, qualification and authority criteria. Other categories may fit better.' },
      { question: 'Do I have to cancel my current visa first?', answer: 'Do not cancel a current residence visa until the correct sequence is confirmed. The existing status is commonly retained until pre-approval or the authority directs otherwise.' },
      { question: 'Can I apply while outside the UAE?', answer: 'Some property nominations can be initiated from abroad, with an entry permit issued for required in-country steps. Other routes may require UAE residence.' },
    ],
    tabs: [
      { label: 'Property investors', title: 'Real estate investors', detail: 'A Dubai property investment valued at AED 2 million or more may qualify for a 10-year Golden Visa route, subject to DLD and immigration review.', points: ['Title deed or eligible off-plan ownership proof', 'DLD valuation where required', 'Mortgage and joint-ownership evidence if applicable'] },
      { label: 'Professionals', title: 'High earners & professionals', detail: 'Skilled professionals may qualify based on role, salary, degree, professional licence and employer documentation. The required combination depends on current rules.', points: ['Labour contract and salary certificate', 'Attested university degree', 'Valid professional licence where applicable'] },
      { label: 'Entrepreneurs', title: 'Entrepreneurs', detail: 'Entrepreneur routes assess the business, investment, project or approved incubator evidence against category-specific nomination criteria.', points: ['Trade licence and ownership records', 'Project, investment or incubator evidence', 'Approvals and recommendation letters where required'] },
      { label: 'Students', title: 'Outstanding students', detail: 'High-performing school and university graduates may be nominated based on academic achievement, institution and authority criteria.', points: ['Official transcripts and graduation certificate', 'School / university recommendation', 'Passport and current residence details'] },
    ],
    benefits: [
      { title: 'Long-term security', description: 'Residence validity of up to ten years, subject to the qualifying category and ongoing conditions.' },
      { title: 'Family sponsorship', description: 'Sponsor eligible family members under the applicable Golden Visa rules.' },
      { title: 'Flexible residency', description: 'Long-term residence designed for investors, professionals, entrepreneurs and exceptional students.' },
      { title: 'Business continuity', description: 'Plan personal residence and business commitments together with fewer short-term renewal cycles.' },
    ],
    interaction: 'golden',
    formTitle: 'Book a Golden Visa route review',
    formDescription: 'Tell us which category you are considering and an advisor can map the documents, authorities and next steps.',
  },
  'Property Visa': {
    title: 'Property Visa',
    eyebrow: 'Property-linked residency',
    description: 'Compare Dubai’s property investor and Golden Visa pathways, verify ownership evidence and coordinate the DLD and immigration stages.',
    heroMetric: 'AED 2M+',
    heroLabel: 'property value route for 10-year Golden Visa',
    introTitle: 'Choose the route that matches the ownership record',
    intro: 'Property value, title type, co-ownership, age and the issuing authority determine the available residence route. An SPA alone is not proof of registered ownership for visa purposes; use a DLD title deed or eligible Oqood and confirm the current threshold before you proceed.',
    metrics: [{ value: 'AED 2M+', label: '10-year Golden Visa property route' }, { value: 'No minimum*', label: 'sole-owner 2-year investor route; joint share above AED 400K' }, { value: 'DLD review', label: 'route and ownership evidence dependent' }],
    highlights: [
      { title: '10-year Golden Visa', description: 'A Dubai property or combined eligible property value of AED 2 million or more may qualify, subject to the authority’s review.' },
      { title: '2-year investor residence', description: 'The reference route describes no minimum property value for a sole owner and a joint ownership share above AED 400,000; title and current DLD criteria must be confirmed.' },
      { title: 'Retirement route', description: 'Applicants aged 55 or older may have a separate 5-year retirement route based on qualifying property value and additional conditions.' },
    ],
    processTitle: 'Dubai Land Department to residence issuance',
    process: [
      { title: 'Title and value review', detail: 'Confirm DLD ownership, title type, current valuation, ownership share and mortgage status.' },
      { title: 'DLD eligibility / nomination', detail: 'Submit the property evidence to the relevant DLD channel for eligibility confirmation or nomination.' },
      { title: 'Immigration application', detail: 'Prepare the entry permit or status-change file with the required personal and property documents.' },
      { title: 'Medical, ID and residence', detail: 'Complete medical fitness and Emirates ID steps, then finalize the residence permit.' },
    ],
    documentsTitle: 'Property and applicant checklist',
    documents: ['DLD Title Deed for a ready property or eligible Oqood for off-plan ownership', 'Current DLD valuation certificate if the recorded value needs updating', 'Passport, UAE visa / Emirates ID and recent photograph', 'Mortgage liability letter and bank NOC / no-objection evidence when required', 'Co-owner identity and share evidence for jointly held property', 'Proof of insurance and any dependent documents for family applications'],
    table: {
      title: 'Property visa routes at a glance',
      caption: 'Thresholds are route guides, not a guarantee of approval. Confirm the current DLD and immigration criteria before applying.',
      columns: ['Route', 'Property value / share', 'Validity', 'Key evidence'],
      rows: [
        ['Investor residence', 'No minimum for sole owner; joint share above AED 400,000 (reference guide)', '2 years', 'DLD ownership proof; title, status and current criteria apply'],
        ['Golden Visa', 'AED 2,000,000+', '10 years', 'Title deed / eligible Oqood; DLD valuation or mortgage evidence if needed'],
        ['Retirement residence', 'AED 1,000,000+; applicant aged 55+', '5 years', 'Property evidence and age / other eligibility requirements'],
      ],
    },
    faqs: [
      { question: 'Is an SPA enough for a property visa?', answer: 'No. The application needs DLD-issued ownership evidence such as a title deed for a ready property or eligible Oqood for an off-plan property.' },
      { question: 'Can I combine multiple properties?', answer: 'Eligible property values may be combined for certain routes when the DLD confirms ownership and total value.' },
      { question: 'Can my family apply with me?', answer: 'Eligible dependents can generally be sponsored. Their files require relationship documents and separate government charges.' },
      { question: 'Is the whole process online?', answer: 'Document review and many submissions can be handled remotely, but applicants still need to attend required medical and Emirates ID biometric appointments.' },
    ],
    formTitle: 'Check your property visa route',
    formDescription: 'Share the title type, ownership share and approximate current value for a route and document review.',
  },
  'Newborn Visa': {
    title: 'Newborn Visa',
    eyebrow: 'New arrival, clear steps',
    description: 'A practical newborn residence timeline that keeps birth registration, passport issuance, Emirates ID and visa filing on track.',
    heroMetric: '120 DAYS',
    heroLabel: 'residence application deadline from birth',
    introTitle: 'Start the newborn file as soon as the birth is registered',
    intro: 'A newborn born in the UAE must have a residence visa arranged within 120 days from the date of birth. The deadline covers the full chain from birth certificate and attestations to passport and residence processing. Start early; daily fines may apply after the grace period.',
    metrics: [{ value: 'Day 1–14', label: 'recommended time to begin document preparation' }, { value: '120 days', label: 'deadline counted from birth date' }, { value: '3 stages', label: 'certificate, passport, residence formalities' }],
    notice: { title: '120-day deadline: counted from the date of birth', text: 'Do not wait until the passport is issued to start. Birth certificate, required attestation, passport issuance, Emirates ID and visa steps must all be completed within the allowed period.', tone: 'warning' },
    highlights: [
      { title: 'Certificate first', description: 'Obtain the UAE birth certificate and confirm whether it needs MOFA attestation for your parents’ nationality and embassy process.' },
      { title: 'Passport application', description: 'Apply through the relevant embassy or consulate and check the photo, parent-ID and certificate rules early.' },
      { title: 'Fine prevention', description: 'Track the 120-day deadline from the birth date and keep proof of appointments and submissions in one file.' },
    ],
    processTitle: 'Newborn registration timeline',
    process: [
      { title: 'Birth certificate & attestation', detail: 'Register the birth, obtain the official certificate and complete any required embassy / MOFA attestation.' },
      { title: 'Newborn passport', detail: 'Submit the certificate and parent documents to the relevant embassy or consulate for passport issuance.' },
      { title: 'Dependent entry permit', detail: 'Prepare the sponsor and relationship file and apply for the newborn residence entry permit or status change.' },
      { title: 'Emirates ID & residence', detail: 'Complete the newborn Emirates ID application and finalize residence issuance before the deadline.' },
    ],
    documentsTitle: 'Newborn visa document checklist',
    documents: ['UAE birth certificate and attestation receipts where required', 'Newborn passport and recent passport-format photograph', 'Passports, UAE residence visas and Emirates IDs of both parents', 'Attested marriage certificate if requested by the authority', 'Sponsor salary and accommodation evidence where applicable', 'Application / entry permit number and newborn Emirates ID application'],
    faqs: [
      { question: 'When does the 120-day period start?', answer: 'It is counted from the newborn’s date of birth, not from passport collection or certificate attestation.' },
      { question: 'What happens if the deadline is missed?', answer: 'Overstay fines may apply after the applicable grace period. Contact the relevant authority or an authorized typing centre promptly to verify the file and current amount.' },
      { question: 'Does the newborn need medical fitness?', answer: 'Medical fitness requirements differ by age and application route. Newborns are generally handled differently from adult applicants; confirm the exact steps for your file.' },
      { question: 'Can we start before the passport arrives?', answer: 'Yes. Start preparing the birth certificate, parent records and attestation steps immediately while the passport application is underway.' },
    ],
    formTitle: 'Get a newborn deadline check',
    formDescription: 'Share the birth date, parents’ visa emirate and current document stage to prioritize the next steps.',
  },
  'Maid Visa': {
    title: 'Maid Visa',
    eyebrow: 'Domestic worker sponsorship',
    description: 'Understand sponsor eligibility, deposit and government-cost items, then coordinate domestic worker entry, medical, labour and residence steps.',
    heroMetric: 'ONE FILE',
    heroLabel: 'entry permit through residence issuance',
    introTitle: 'Household sponsorship has specific sponsor and worker conditions',
    intro: 'Domestic worker sponsorship requirements depend on the sponsor’s household status, income, accommodation, nationality and the worker’s circumstances. Salary thresholds and refundable deposits can change by route; get a current official, itemized quote before paying or recruiting.',
    metrics: [{ value: 'Sponsor review', label: 'income, family status and accommodation' }, { value: 'Itemized quote', label: 'government charges and refundable deposit separated' }, { value: 'End-to-end', label: 'permit, medical, contract and residence' }],
    highlights: [
      { title: 'Sponsor eligibility', description: 'Prepare salary evidence, family / marital status and suitable accommodation information for the applicable route.' },
      { title: 'Cost transparency', description: 'Separate government application, medical, Emirates ID, insurance, typing and any refundable deposit in the written quote.' },
      { title: 'Worker protections', description: 'Use the applicable approved channel and make sure contract, insurance and worker obligations are clear before travel.' },
    ],
    processTitle: 'Domestic worker typing and approval flow',
    process: [
      { title: 'Sponsor and worker eligibility', detail: 'Review the sponsor profile, household needs, worker passport and the route permitted for the case.' },
      { title: 'Entry permit & contract', detail: 'Submit the application and employment contract through the relevant authorized channel.' },
      { title: 'Medical & Emirates ID', detail: 'After arrival or status change, complete required medical fitness and Emirates ID formalities.' },
      { title: 'Residence issuance', detail: 'Pay the confirmed government charges, finalize the residence permit and retain receipts and contract records.' },
    ],
    documentsTitle: 'Sponsor and worker documents',
    documents: ['Sponsor passport, Emirates ID and UAE residence visa', 'Sponsor salary certificate / income evidence and accommodation documents', 'Family book or marriage certificate when relevant to eligibility', 'Worker passport, photograph and contact details', 'Signed domestic worker contract and any required job offer / insurance records', 'Application, medical and Emirates ID references after approval'],
    table: {
      title: 'Plan the full sponsorship cost',
      caption: 'Amounts vary by visa duration, emirate, worker route and current authority tariff. Request a dated quote and confirm which deposit is refundable.',
      columns: ['Cost item', 'What it covers', 'Quote treatment'],
      rows: [
        ['Entry permit / status change', 'Immigration application and in-country status change where applicable', 'Government fee'],
        ['Typing and approval', 'Authorized centre processing and contract / labour approvals', 'Government + centre service charge'],
        ['Medical fitness & Emirates ID', 'Required screening and identity-card application', 'Government / centre fee'],
        ['Insurance & refundable deposit', 'Required policy and any route-specific security deposit', 'Policy cost / refundable amount shown separately'],
        ['Residence issuance & service', 'Final residence permit and optional file-management support', 'Government fee + optional service fee'],
      ],
    },
    faqs: [
      { question: 'What is the minimum sponsor salary?', answer: 'There is no single threshold for every domestic-worker route. It depends on the sponsor category and current regulations; have the centre verify the current income requirement before starting.' },
      { question: 'Is a deposit always required?', answer: 'Some routes include a refundable deposit or guarantee. The amount and refund conditions differ, so request written confirmation and an official receipt.' },
      { question: 'Can the worker enter on a visit visa first?', answer: 'Do not treat a visit visa as permission to work. Use the authorized entry permit and employment process before work begins.' },
      { question: 'What is included in end-to-end support?', answer: 'Depending on the route: entry permit or status change, contract typing, medical fitness, Emirates ID and residence issuance coordination.' },
    ],
    formTitle: 'Request a domestic worker visa cost breakdown',
    formDescription: 'Tell us the sponsor emirate, household status and whether the worker is inside or outside the UAE.',
  },
  'Emirates ID': {
    title: 'Emirates ID Services',
    eyebrow: 'Federal identity services',
    description: 'Choose the right Emirates ID service—new application, renewal or replacement—and understand biometrics, tracking and delivery.',
    heroMetric: '3–5 DAYS',
    heroLabel: 'typical processing after application',
    introTitle: 'The right application depends on the cardholder’s status',
    intro: 'An Emirates ID is required for UAE residents of every age. Application type, residence validity, biometrics and delivery address determine the next steps. Use ICP’s official status service with your PRAN or application number for direct tracking.',
    metrics: [{ value: '24–48h', label: 'typical card printing after biometrics' }, { value: 'AED 150', label: 'optional Fawri fast service at ICP main centres' }, { value: '30 days', label: 'renewal grace period after expiry (confirm current rules)' }],
    highlights: [
      { title: 'New application', description: 'Usually linked to a new or renewed residence file; first-time adult applicants attend an ICP biometric appointment.' },
      { title: 'Renewal', description: 'Renew before or promptly after expiry. Biometrics may be reused when ICP does not request a new appointment.' },
      { title: 'Lost or damaged card', description: 'Report the loss / damage and apply for a replacement through ICP; protect your ID number and keep the request reference.' },
    ],
    processTitle: 'From application number to delivery',
    process: [
      { title: 'Select service type', detail: 'Choose a new, renewal or replacement application and check that the residence information is correct.' },
      { title: 'Submit and pay', detail: 'Complete the ICP application, upload the required records and keep the PRAN / application number.' },
      { title: 'Biometrics if requested', detail: 'Attend the designated ICP centre with the original passport and appointment confirmation.' },
      { title: 'Track and receive', detail: 'Check status on the ICP website or app; follow courier notifications for card delivery.' },
    ],
    documentsTitle: 'What to bring or upload',
    documents: ['Passport and valid residence visa / electronic residence details', 'Recent personal photograph meeting ICP specifications', 'Current Emirates ID for renewal or damaged-card replacement', 'PRAN / application reference for tracking', 'Parent or guardian Emirates ID and birth certificate for a child', 'Police report / loss declaration where required for a lost-card replacement'],
    table: {
      title: 'New, renewal or replacement?',
      caption: 'Final steps and fees depend on the cardholder category and ICP’s request.',
      columns: ['Service', 'Typical requirement', 'Biometrics', 'Tracking'],
      rows: [
        ['New application', 'Residence application / new eligibility, passport and photo', 'First-time adult applicants; child rules differ', 'PRAN on ICP website or app'],
        ['Renewal', 'Current ID, passport and valid / renewed residence details', 'Only if ICP requests it', 'PRAN or Emirates ID number'],
        ['Lost / damaged replacement', 'Identity evidence and replacement request; loss report if requested', 'May be requested for verification', 'Replacement application reference'],
      ],
    },
    faqs: [
      { question: 'How do I check my Emirates ID application?', answer: 'Use the official ICP website or UAE ICP app and enter your PRAN / application number. Status tracking is free.' },
      { question: 'Can children get an Emirates ID without fingerprints?', answer: 'Children under 15 generally do not provide fingerprints; the authority may require a photograph and guardian documents.' },
      { question: 'Can I apply while outside the UAE?', answer: 'Some renewals can be prepared remotely, but first-time applicants may need to be inside the UAE for biometrics. Confirm the appointment requirement with ICP.' },
      { question: 'When does the late renewal fine begin?', answer: 'The cited service guidance notes a 30-day grace period and AED 20 per day after that, capped at AED 1,000. Check current ICP rules for your case.' },
    ],
    formTitle: 'Need help with an Emirates ID application?',
    formDescription: 'Tell us whether it is a new card, renewal or replacement and include the application stage—not your full ID number.',
  },
  'PRO Services': {
    title: 'Corporate PRO Services',
    eyebrow: 'Corporate government relations',
    description: 'Outsource recurring UAE government transactions or request one-off individual PRO support with clear scope, ownership and reporting.',
    heroMetric: 'ON-DEMAND',
    heroLabel: 'PRO coverage for your business',
    introTitle: 'Keep business-critical government files moving',
    intro: 'A PRO coordinates government counters and digital systems across immigration, labour, typing, medical and Emirates ID services. A monthly retainer suits repeat company needs; one-off support can work better for an individual permit or a specific transaction. Government charges depend on the company’s MOHRE category and transaction type.',
    metrics: [{ value: 'MOHRE', label: 'labour permits and contracts' }, { value: 'GDRFA / ICP', label: 'residence and immigration files' }, { value: 'One-time or retainer', label: 'scope aligned to monthly volume' }],
    highlights: [
      { title: 'Corporate outsourcing', description: 'A named support team, renewal calendar and monthly tracker for visas, establishment cards, licences and employee lifecycle actions.' },
      { title: 'Individual PRO', description: 'Task-based assistance with an employee visa, dependent application, document attestation or a specific authority submission.' },
      { title: 'Clear fee separation', description: 'Government fees, centre charges, refundable deposits, VAT and professional service charges are listed separately.' },
    ],
    processTitle: 'From request to completed transaction',
    process: [
      { title: 'Scope and SLA', detail: 'Agree whether the request is a recurring retainer or a one-time transaction, including authorities, turnaround and reporting.' },
      { title: 'Establishment and file check', detail: 'Review trade licence, establishment card, MOHRE category and employee or sponsor records.' },
      { title: 'Submission and tracking', detail: 'Coordinate the required applications across MOHRE, GDRFA / ICP, medical fitness and Emirates ID channels.' },
      { title: 'Closure and calendar', detail: 'Share receipts and status updates, then schedule relevant renewals, cancellations or upcoming obligations.' },
    ],
    documentsTitle: 'Corporate onboarding checklist',
    documents: ['Valid trade licence and establishment / immigration card', 'Authorized signatory passport, Emirates ID and UAE Pass access where appropriate', 'MOHRE company category and quota details', 'Employee passport, photo, signed offer and qualification records as relevant', 'Current labour and residence records for renewals or cancellations', 'Company contact, escalation and approval matrix'],
    table: {
      title: 'Retainer or individual PRO support?',
      caption: 'The best model depends on transaction volume, company category and required response times.',
      columns: ['Model', 'Best for', 'Typical scope'],
      rows: [
        ['Corporate outsourcing', 'Companies with regular hiring, renewals and government submissions', 'Named coordinator, tracker, visa and permit lifecycle, establishment renewals'],
        ['Individual PRO service', 'A single employee, family or company transaction', 'Defined task, document review, application preparation and follow-up'],
        ['Project support', 'Licence change, quota planning or multi-employee onboarding', 'Time-bound plan, authority sequence and milestone reporting'],
      ],
    },
    faqs: [
      { question: 'Why does one company pay a different MOHRE labour fee?', answer: 'The company’s MOHRE category, employee profile and permit type affect labour charges. Confirm the live tariff and category before budgeting.' },
      { question: 'Can I hire someone who already has a family or Golden Visa?', answer: 'A work permit may be available without a new residence visa, subject to MOHRE rules and the employee’s status.' },
      { question: 'Can you process cancellations and renewals?', answer: 'Yes. The correct sequence depends on whether the worker remains in the UAE and the applicable employment settlement and immigration steps.' },
      { question: 'Are government fees included in the retainer?', answer: 'Government fees and third-party charges are usually separate from a professional service retainer and should be itemized in the proposal.' },
    ],
    formTitle: 'Discuss a corporate PRO retainer',
    formDescription: 'Share your company activity, employee count and expected monthly transactions for a scope proposal.',
  },
  'Amer Center': {
    title: 'Amer Center Services',
    eyebrow: 'Dubai immigration services',
    description: 'Prepare Dubai visa and residence transactions for submission through an authorized Amer centre or official GDRFA digital channels.',
    heroMetric: 'GDRFA',
    heroLabel: 'Dubai immigration authority',
    introTitle: 'Amer centres submit applications; GDRFA decides them',
    intro: 'An Amer centre is a privately operated service centre licensed by GDRFA Dubai to type and submit immigration applications. It is not itself a government office and cannot approve a visa. Federal ICP channels handle immigration matters for other emirates.',
    metrics: [{ value: 'Dubai only', label: 'Amer is the GDRFA Dubai service channel' }, { value: 'Walk-in', label: 'many centres accept walk-ins; hours vary' }, { value: 'Official channels', label: 'GDRFA website and smart app are available online' }],
    highlights: [
      { title: 'Residence & entry permits', description: 'Family, newborn, domestic worker, visit, Golden Visa, renewals, cancellations and change-of-status applications.' },
      { title: 'Company immigration', description: 'Establishment card and related immigration services, with separate labour transactions handled through MOHRE / Tasheel.' },
      { title: 'Express / VIP processing', description: 'Some centres offer a paid priority desk. It can shorten centre waiting time but does not guarantee government approval or processing speed.' },
    ],
    processTitle: 'Before you visit an Amer centre',
    process: [
      { title: 'Confirm the authority', detail: 'Use Amer for GDRFA Dubai cases. For visas issued by other emirates, check the federal ICP channel.' },
      { title: 'Ask for the exact checklist', detail: 'Requirements differ by transaction and sponsor; confirm originals, copies, photos and any attested certificates.' },
      { title: 'Submit and pay', detail: 'Review the application data before submission and ask for an itemized receipt separating government fees and centre charges.' },
      { title: 'Track with the reference', detail: 'Keep the application number and use official GDRFA channels to check for status or missing requirements.' },
    ],
    documentsTitle: 'General submission checklist',
    documents: ['Sponsor passport, Emirates ID and UAE visa copy', 'Applicant passport copy and recent white-background photo', 'Attested marriage / birth certificate and salary evidence for family cases', 'Trade licence and establishment card for company immigration requests', 'Application or previous file number for renewals and status change', 'Original documents requested for the specific service'],
    faqs: [
      { question: 'Is an Amer centre a government office?', answer: 'No. It is a private service centre licensed and supervised by GDRFA Dubai. GDRFA makes the immigration decision.' },
      { question: 'Can I visit an Amer centre outside Dubai?', answer: 'Amer is for GDRFA Dubai immigration services. Other emirates use federal ICP channels.' },
      { question: 'Do I need an appointment?', answer: 'Many centres accept walk-ins, but hours and appointment policies vary. Contact the selected centre before travelling.' },
      { question: 'How much will the centre charge?', answer: 'Government fees are set by the authority; each centre may charge a separate typing or service fee. Request an itemized quote and receipt.' },
    ],
    formTitle: 'Arrange an Amer appointment checklist',
    formDescription: 'Tell us the transaction type and visa emirate; we will confirm the likely documents and appropriate channel.',
  },
  'Attestation': {
    title: 'Document Attestation',
    eyebrow: 'UAE document legalization',
    description: 'Map the attestation chain for personal, educational or commercial records—from the issuing country through UAE MOFA.',
    heroMetric: 'MOFA UAE',
    heroLabel: 'final UAE attestation stage',
    introTitle: 'The attestation path depends on where a document was issued',
    intro: 'A document issued abroad usually needs verification in its country of origin, UAE Embassy / Consulate attestation and final UAE MOFA attestation. The exact sequence changes by country, document type, language and intended use. Confirm it before sending original documents.',
    metrics: [{ value: 'Country-specific', label: 'steps depend on document origin' }, { value: 'MOFA UAE', label: 'final UAE government attestation stage' }, { value: 'Arabic', label: 'certified translation when required for use' }],
    highlights: [
      { title: 'Educational', description: 'Degrees, diplomas and transcripts may need university, education authority and foreign-affairs verification before UAE Embassy and MOFA.' },
      { title: 'Personal', description: 'Birth, marriage, divorce and police certificates follow a country-specific chain and may need certified Arabic translation.' },
      { title: 'Commercial', description: 'Company, trade and corporate records require authority and chamber / notary stages appropriate to their place of issue.' },
    ],
    processTitle: 'Interactive attestation workflow',
    process: [
      { title: 'Issuing authority', detail: 'Confirm the original issuer and whether notarization, registrar or ministry authentication is required.' },
      { title: 'Home-country verification', detail: 'Complete the foreign-affairs / relevant authority stage in the country where the document was issued.' },
      { title: 'UAE Embassy / Consulate', detail: 'Obtain UAE diplomatic mission attestation in the document’s country of origin, if required.' },
      { title: 'MOFA UAE & translation', detail: 'Complete final MOFA UAE attestation and certified Arabic translation when needed for the intended transaction.' },
    ],
    documentsTitle: 'Before handing over a document',
    documents: ['Original document and a clear colour scan of every page', 'Passport copy of the document holder or authorized representative', 'Issuing country and city, issue date and document type', 'Intended UAE use: visa, court, school, employment, banking or business', 'Prior attestation stamps and certified translation, if already completed', 'Authorization letter if a third party will submit or collect the original'],
    faqs: [
      { question: 'Can the same attestation sequence be used for every country?', answer: 'No. The home-country chain varies by jurisdiction and document type. Verify the sequence with the UAE Embassy / Consulate and MOFA before submission.' },
      { question: 'When is Arabic translation required?', answer: 'It is often required for Arabic-language UAE authority, court or immigration use. The translator must meet the relevant certification requirements.' },
      { question: 'Can a copy be attested instead of the original?', answer: 'This depends on the document and authority. Many processes require the original or a certified true copy; confirm before dispatch.' },
      { question: 'Do company documents follow the personal-document route?', answer: 'No. Commercial records may require chamber, notary or corporate authority verification that does not apply to personal certificates.' },
    ],
    interaction: 'attestation',
    formTitle: 'Get a country-specific attestation sequence',
    formDescription: 'Choose the issuing country and document type above, then share the intended use for a tailored review.',
  },
  'Legal Translation': {
    title: 'Legal Translation',
    eyebrow: 'Ministry of Justice certified',
    description: 'Request a certified legal translation for court, notary, immigration, property and commercial use in the UAE.',
    heroMetric: 'MOJ',
    heroLabel: 'Ministry of Justice certified translation',
    introTitle: 'Legal wording, names and seals must carry through accurately',
    intro: 'Official use may require translation by a UAE Ministry of Justice licensed legal translator. Certification requirements vary by receiving authority and document. Share clear scans for an initial quote; confirm whether the authority needs original pages, stamps or a particular language pair.',
    metrics: [{ value: 'Arabic ↔ English', label: 'most-requested language pair' }, { value: 'Certified', label: 'MOJ translator route for official use' }, { value: 'Quote first', label: 'page count and language set the estimate' }],
    tags: [{ title: 'Supported language pairs', values: ['Arabic', 'English', 'French', 'Russian', 'Urdu', 'Hindi', 'German', 'Spanish', 'Chinese', 'Turkish'] }],
    highlights: [
      { title: 'Court & legal', description: 'Powers of attorney, court judgments, pleadings, contracts, affidavits and wills.' },
      { title: 'Personal records', description: 'Marriage and birth certificates, academic records, passports, licences and family documents.' },
      { title: 'Commercial', description: 'Trade licences, memoranda, tenders, agreements, corporate resolutions and banking documents.' },
    ],
    processTitle: 'From clear scan to certified copy',
    process: [
      { title: 'Upload a scan for review', detail: 'Provide every page, stamp and reverse side. Flag handwritten sections or low-resolution images.' },
      { title: 'Confirm use and language', detail: 'Identify the receiving authority, language pair, certification type, turnaround and any original-copy needs.' },
      { title: 'Translate and review', detail: 'The legal translator prepares the text and checks names, dates, figures and official terminology.' },
      { title: 'Certify and deliver', detail: 'Receive the translated document in the agreed format and confirm any attestation requirement with the receiving office.' },
    ],
    documentsTitle: 'Files to include in a quote request',
    documents: ['Legible full scan or PDF, including stamps, signatures and blank pages with endorsements', 'Source and target language', 'Country / UAE authority where the translation will be submitted', 'Required completion date and number of physical certified copies', 'Reference spelling of names from passport or Emirates ID', 'Any previous translation or glossary for consistent company / legal terms'],
    faqs: [
      { question: 'What does a MOJ-certified translation mean?', answer: 'The translation is completed and certified by a translator licensed by the UAE Ministry of Justice for the relevant language pair.' },
      { question: 'Which languages can you support?', answer: 'Arabic and English are common; French, Russian, Urdu, Hindi and other language pairs may be available depending on the licensed translator.' },
      { question: 'Can I get a quote before uploading the original?', answer: 'Yes. A clear scan is usually enough for an initial page-count and language quote. Attach the original in the secure channel requested for the final order.' },
      { question: 'Will every authority accept the same translation?', answer: 'Not always. The receiving court, notary or government department determines certification and attestation requirements.' },
    ],
    interaction: 'translation',
    formTitle: 'Request a certified translation quote',
    formDescription: 'Select the file above to note its type and page count; the file stays on your device until you choose to attach it in WhatsApp.',
  },
  'Power of Attorney (POA)': {
    title: 'Power of Attorney (POA)',
    eyebrow: 'UAE legal representation',
    description: 'Prepare a lawyer-reviewed power of attorney for the authority you intend to delegate, with drafting, translation and notarization support in one guided service.',
    heroMetric: 'DRAFT → NOTARY',
    heroLabel: 'a guided POA preparation journey',
    introTitle: 'Make the delegated authority precise and usable',
    intro: 'A power of attorney authorizes an appointed agent to act for you within stated limits. Start by describing the transaction and the receiving authority: broad general wording may be unsuitable for a specific property, vehicle or company matter. The notary and organization receiving the POA confirm the wording, identity checks and execution method they will accept.',
    metrics: [{ value: '5 POA types', label: 'general, personal, property, corporate and vehicle' }, { value: 'Online support', label: 'remote notarization depends on applicant and document eligibility' }, { value: 'Itemized quote', label: 'drafting, translation and notary charges scoped separately' }],
    highlights: [
      { title: 'General & personal', description: 'Set defined authority for personal administration, family matters or representation, with clear limits and duration.' },
      { title: 'Property & vehicle', description: 'Identify the asset and transaction, such as a sale, purchase, management task or vehicle registration action.' },
      { title: 'Corporate', description: 'Specify company representation and the permitted signing, licensing, banking or operational actions.' },
    ],
    processTitle: 'From first consultation to notarized POA',
    process: [
      { title: 'Personalized quote and scope', detail: 'Confirm the POA type, principal and agent, intended use, powers, exclusions, duration, language and signing preference.' },
      { title: 'Drafting and client review', detail: 'Prepare the draft for review. Check every name, ID detail, asset reference and authority before approving the final wording.' },
      { title: 'Translation and notarization', detail: 'Arrange the required legal translation and coordinate an eligible remote video or in-person notary appointment.' },
      { title: 'Executed document and next steps', detail: 'Receive the completed document and confirm any further attestation or original-document requirements with the organization receiving it.' },
    ],
    documentsTitle: 'POA preparation checklist',
    documents: ['Passport and Emirates ID / UAE residence copy for the principal', 'Passport and contact details for the appointed agent', 'Exact powers, limits, duration and whether substitution is allowed', 'Title deed, vehicle registration or company licence for asset-specific POAs', 'Company authorization / board resolution if a corporate principal is involved', 'Intended use and country of use to confirm notarization and attestation steps'],
    table: {
      title: 'POA pricing components',
      caption: 'A written quote is provided after confirming type, language, signing method and urgency. Official notary charges can change.',
      columns: ['Component', 'What is included', 'Pricing basis'],
      rows: [
        ['Consultation & drafting', 'Scope review and lawyer-prepared draft', 'Document complexity and number of principals'],
        ['Legal translation', 'Certified Arabic / English or other available pair', 'Language pair and page count'],
        ['Notarization', 'Appointment preparation and execution coordination', 'Notary channel, number of signers and service speed'],
        ['Attestation / courier', 'Additional legalization or delivery, if needed', 'Destination and delivery options'],
      ],
    },
    faqs: [
      { question: 'Can I prepare a power of attorney without visiting a notary office?', answer: 'Some eligible applicants and POA types can use remote video notarization. The notary must confirm identity, jurisdiction and document requirements; an office appointment may still be necessary.' },
      { question: 'Do I need to be a UAE resident to make a POA?', answer: 'Residency is not the only factor. The signing location, applicant identity, notary process and intended use determine the available route. Share the country where you will sign so the execution steps can be checked.' },
      { question: 'Can a POA be drafted in English only?', answer: 'The language accepted depends on the notary and receiving organization. UAE use may require a certified Arabic translation or bilingual format; confirm before approving the final draft.' },
      { question: 'Can a POA authorize someone to sell my Dubai property?', answer: 'A property POA can be prepared for a defined transaction, but the asset details and exact powers must meet the requirements of the notary and relevant property authority. Confirm acceptance before signing.' },
      { question: 'Should I choose a general or specific POA?', answer: 'Use only the authority needed. Property, company and vehicle transactions often need specific wording that the receiving institution accepts.' },
      { question: 'How long does a POA take?', answer: 'Timing depends on drafting approval, translation, identity checks and notary availability. A complete draft and ID set can reduce avoidable revisions.' },
      { question: 'Can I use a UAE POA abroad?', answer: 'The receiving country may require additional attestations or a different execution format. Confirm with the recipient before notarization.' },
    ],
    interaction: 'poa',
    formTitle: 'Book an online POA consultation',
    formDescription: 'Select a POA type, then share its intended use and preferred language. Do not send original identity documents through this form.',
  },
  'Wills & Last Testament': {
    title: 'Wills & Last Testament',
    eyebrow: 'UAE estate planning',
    description: 'Compare will-registration routes, document asset and guardianship wishes, and prepare a clear legal plan for your family.',
    heroMetric: 'PLAN AHEAD',
    heroLabel: 'assets, dependents and guardianship',
    introTitle: 'A will records your wishes and reduces uncertainty',
    intro: 'A registered will can document how assets and responsibilities should be handled, subject to the applicable UAE law and registration route. DIFC and Dubai Courts have different eligibility, language, registration and asset-scope considerations. Get legal advice on the right venue for your family and estate.',
    metrics: [{ value: 'DIFC / Courts', label: 'compare registration venue and scope' }, { value: 'Guardianship', label: 'record eligible minor-child wishes' }, { value: 'Asset map', label: 'UAE and international assets need careful review' }],
    highlights: [
      { title: 'Guardianship planning', description: 'Document guardian wishes for minor children and confirm the formal registration and appointment rules.' },
      { title: 'Asset protection', description: 'Identify real estate, bank accounts, company interests and other assets, including where each is located.' },
      { title: 'Executor instructions', description: 'Set out executors, beneficiaries and distribution instructions in a clear, internally consistent document.' },
    ],
    processTitle: 'From family and asset review to registration',
    process: [
      { title: 'Family and estate consultation', detail: 'Map family structure, dependents, assets, residence, citizenship and the jurisdictions involved.' },
      { title: 'Choose registration route', detail: 'Compare the DIFC Wills Service and Dubai Courts options with a qualified legal advisor.' },
      { title: 'Draft and review', detail: 'Prepare beneficiary, executor, guardianship and asset provisions and verify names and title information.' },
      { title: 'Sign and register', detail: 'Complete the relevant appointment, language and registration formalities; store a copy and revisit after major life changes.' },
    ],
    documentsTitle: 'Estate planning preparation list',
    documents: ['Passport, Emirates ID and residence details of the testator', 'Spouse, children, dependents and proposed guardian / executor details', 'Dubai and UAE property title deeds and ownership shares', 'Bank, investment, company and insurance asset summary', 'Any foreign assets and the country where each is held', 'Existing will, marriage certificate and other relevant legal records'],
    table: {
      title: 'DIFC Will and Dubai Courts Will',
      caption: 'This is a high-level comparison, not legal advice. Confirm current eligibility, available will types, language and registration fees with the registry.',
      columns: ['Consideration', 'DIFC Wills Service', 'Dubai Courts'],
      rows: [
        ['Registry', 'DIFC Wills Service registration framework', 'Dubai Courts registration framework'],
        ['Language & execution', 'English-language route and prescribed execution formalities may be available', 'Arabic-language execution / certified translation requirements may apply'],
        ['Asset scope', 'Available asset categories and geographic scope depend on current rules and will type', 'Scope and enforceability depend on the will type and applicable law'],
        ['Best next step', 'Check DIFC eligibility and current registration route', 'Check court process, language and document requirements'],
      ],
    },
    faqs: [
      { question: 'Who should consider registering a will?', answer: 'Anyone with property, bank balances, business interests, dependents or specific wishes may benefit from a properly prepared will.' },
      { question: 'Can a will include guardianship wishes?', answer: 'Guardianship provisions may be available for eligible minor children. Confirm guardian eligibility and the correct registry process with a UAE-qualified legal advisor.' },
      { question: 'Which is better: DIFC or Dubai Courts?', answer: 'It depends on eligibility, language, asset type, jurisdiction and family circumstances. Review both routes with qualified counsel before selecting one.' },
      { question: 'When should I update a registered will?', answer: 'Review it after marriage, divorce, a birth, a move, acquiring or selling major assets, or a change to the proposed executors or guardians.' },
    ],
    formTitle: 'Request a free will-planning consultation',
    formDescription: 'Share the broad asset and family-planning topics you want to cover. Do not include account numbers or confidential asset statements.',
  },
  'DLD Trustee Services': {
    title: 'DLD Trustee Services',
    eyebrow: 'Dubai property transactions',
    description: 'Prepare for a property transfer, gift, mortgage registration or release with a practical buyer-and-seller trustee checklist.',
    heroMetric: 'DLD',
    heroLabel: 'Dubai Land Department transaction support',
    introTitle: 'A ready transaction file prevents last-minute trustee delays',
    intro: 'Property trustee transactions require coordinated buyer and seller identity documents, a developer NOC where applicable, bank liability / release paperwork and payment arrangements. The trustee verifies the transaction; confirm the selected centre’s exact list and live fees before the appointment.',
    metrics: [{ value: 'Buyer + seller', label: 'both sides should confirm names and documents' }, { value: 'NOC first', label: 'developer clearance may be needed for transfer' }, { value: '4%', label: 'standard DLD sale transfer fee; exceptions may apply' }],
    highlights: [
      { title: 'Property sale transfer', description: 'Review buyer / seller records, sale details, developer NOC and appointment readiness.' },
      { title: 'Mortgage registration or release', description: 'Coordinate bank NOC, liability letter, settlement proof and mortgage registration / release steps.' },
      { title: 'Gift transfer & title deed', description: 'Prepare relationship proof, valuation, POA checks and supporting documents for an eligible family gift or title service.' },
    ],
    processTitle: 'Dubai Land Department registration workflow',
    process: [
      { title: 'Agree sale and clear liabilities', detail: 'Confirm the sale contract, title details, seller authority, outstanding service charges and any mortgage settlement.' },
      { title: 'Obtain NOC and bank documents', detail: 'Request the developer NOC and bank liability / release letter where applicable.' },
      { title: 'Trustee file check', detail: 'Buyer and seller present identity, transaction and payment records; the trustee verifies the transfer package.' },
      { title: 'Register and issue title', detail: 'Pay confirmed DLD and trustee charges, complete registration and receive the updated title deed.' },
    ],
    documentsTitle: 'Buyer and seller appointment checklist',
    documents: ['Original Emirates ID and passport copies for buyer and seller', 'Current title deed and signed sale / transfer agreement', 'Developer NOC and service-charge clearance where applicable', 'Bank liability letter, settlement proof and release NOC for mortgaged property', 'Valid POA and supporting identity documents for represented parties', 'Manager’s cheque / payment instructions confirmed with the trustee centre'],
    table: {
      title: 'Common Dubai transfer cost items',
      caption: 'Illustrative standard charges only. Rates, VAT, property type and transaction route can change the payable total; get written confirmation.',
      columns: ['Charge', 'Common basis', 'Confirm before appointment'],
      rows: [
        ['DLD sale registration', 'Typically 4% of the sale value, often split between buyer and seller by agreement', 'Current DLD rule and transaction category'],
        ['Trustee centre fee', 'Centre fee varies by transaction and property value', 'VAT and any extra service charge'],
        ['Developer NOC', 'Set by the developer / community', 'Clearance and issue turnaround'],
        ['Mortgage registration / release', 'Bank and DLD charges depend on loan / property details', 'Liability letter and settlement figure'],
      ],
    },
    faqs: [
      { question: 'Who pays the 4% DLD transfer fee?', answer: 'The standard sale transfer fee is commonly 4% of the sale value, but buyer / seller allocation is often agreed in the sale contract. Verify the current charge and any exemptions.' },
      { question: 'Can a representative attend for the buyer or seller?', answer: 'A valid POA may be accepted if it grants the required powers and meets the trustee’s execution and attestation rules. Confirm it before booking.' },
      { question: 'What is needed for a mortgage release?', answer: 'The bank’s liability letter, settlement and release documents are central; exact trustee requirements depend on the lender and transaction.' },
      { question: 'Do both parties need to attend?', answer: 'Attendance or valid representation depends on the transaction and trustee process. Confirm the appointment requirements with the selected centre.' },
    ],
    formTitle: 'Prepare a DLD trustee appointment',
    formDescription: 'Choose sale, gift, mortgage registration or release and tell us whether the property is financed.',
  },
  'Property Revaluation': {
    title: 'Property Revaluation',
    eyebrow: 'Official DLD valuation support',
    description: 'Request an official property valuation review for Golden Visa eligibility, a sale, refinancing, gifting or an audit.',
    heroMetric: 'DLD',
    heroLabel: 'official property valuation certificate',
    introTitle: 'Use an official valuation for the transaction that needs it',
    intro: 'A current DLD valuation can support residence eligibility, sale planning, a mortgage review, nominal gift transfer calculations and court or audit matters. The authority assesses the property and supporting records; a revaluation is not a guaranteed increase over the existing title value.',
    metrics: [{ value: 'Residency', label: 'property threshold review for visa routes' }, { value: 'Refinance', label: 'bank may request an official valuation' }, { value: 'DLD certificate', label: 'official valuation output' }],
    highlights: [
      { title: 'Golden Visa & retirement', description: 'Check whether current property value meets the threshold for an eligible long-term or retirement residence route.' },
      { title: 'Sale, gift and transfer', description: 'Use an official value where required for sale decisions, DLD transfer calculations or family gifting.' },
      { title: 'Mortgage, court and audit', description: 'Support refinancing, estate proceedings, company asset review and other formal valuation needs.' },
    ],
    processTitle: 'Official DLD certificate process',
    process: [
      { title: 'Confirm valuation purpose', detail: 'State whether the valuation is for residency, refinancing, transfer, court or business reporting.' },
      { title: 'Assemble the property file', detail: 'Collect title deed, owner identity, unit details, floor plan and any requested prior valuation or mortgage records.' },
      { title: 'Submit through the official channel', detail: 'Prepare the DLD valuation application, pay the confirmed fee and arrange inspection if required.' },
      { title: 'Receive and review certificate', detail: 'Check owner and property details on the issued certificate before using it with a bank, DLD or immigration authority.' },
    ],
    documentsTitle: 'Valuation audit checklist',
    documents: ['DLD title deed and plot / unit number', 'Owner passport, Emirates ID and contact details', 'Property type, location, size and current use', 'Floor plan, recent photographs or inspection access where requested', 'Mortgage details and bank request for refinancing cases', 'Prior valuation, sale comparables or court / company instruction if relevant'],
    faqs: [
      { question: 'Does the DLD valuation guarantee a higher value?', answer: 'No. DLD makes its own assessment based on current property and market information; the result can differ from an owner’s estimate.' },
      { question: 'Can a new valuation support a Golden Visa application?', answer: 'It may help establish current qualifying property value. Immigration and DLD still decide eligibility and evidence acceptance.' },
      { question: 'Will an inspection be required?', answer: 'The authority may request more information, photographs or access to the unit depending on the case and property type.' },
      { question: 'Can I use the same certificate for a bank and immigration?', answer: 'Confirm the certificate purpose, validity and acceptance rules with each receiving authority before relying on it.' },
    ],
    formTitle: 'Request a property valuation file review',
    formDescription: 'Tell us the property type and purpose—residency, sale, refinancing, gift or court use.',
  },
  'Medical & EID': {
    title: 'Medical Fitness & EID Locations',
    eyebrow: 'Medical fitness and biometrics',
    description: 'Find DHA medical fitness and ICP Emirates ID biometric centres in Dubai, compare express options and arrive prepared.',
    heroMetric: 'DHA + ICP',
    heroLabel: 'medical fitness and identity appointments',
    introTitle: 'Choose the right centre for each required appointment',
    intro: 'Residence applicants may need a DHA medical fitness test and a separate ICP Emirates ID biometric appointment. VIP or express services may be available at selected facilities for an extra fee; they do not change medical eligibility or guarantee visa approval.',
    metrics: [{ value: 'Blood test', label: 'screening required for adult applicants' }, { value: 'Chest X-ray', label: 'may be part of medical fitness screening' }, { value: 'Two authorities', label: 'DHA medical and ICP biometrics are separate steps' }],
    highlights: [
      { title: 'VIP / express screening', description: 'Selected medical fitness centres offer paid priority options. Confirm availability, fee and reporting time before booking.' },
      { title: 'Medical fitness', description: 'Bring the passport, application / UID details and appointment confirmation; follow facility instructions for the required test.' },
      { title: 'Emirates ID biometrics', description: 'Attend the ICP-designated centre with the original passport and appointment notice; children may have different requirements.' },
    ],
    processTitle: 'Appointment-day preparation',
    process: [
      { title: 'Check your medical application', detail: 'Confirm the DHA centre, service speed, appointment time and documents on the medical fitness application.' },
      { title: 'Complete blood test and X-ray', detail: 'Follow the centre’s fasting, medication and health instructions; ask the clinic in advance if you have a medical concern.' },
      { title: 'Book / attend ICP biometrics', detail: 'Use the ICP appointment notice and take the original passport for fingerprints and photograph if requested.' },
      { title: 'Track results and ID', detail: 'Use the application references to follow medical results and Emirates ID status with the respective authorities.' },
    ],
    documentsTitle: 'What to carry',
    documents: ['Original passport and valid UAE entry permit / residence file', 'Medical fitness application or UID / unified number', 'Emirates ID application reference and ICP appointment confirmation', 'Recent passport-size photograph if requested by the facility', 'Glasses / contact lens details or medical records if relevant to the test', 'Payment method for centre charges and any optional express service'],
    faqs: [
      { question: 'Can I choose any medical centre?', answer: 'Use a DHA-approved medical fitness centre that supports your selected service. Verify current availability and the correct application before travelling.' },
      { question: 'Do I need to fast before a medical fitness test?', answer: 'Follow the instructions on your appointment or ask the medical centre. Do not fast unless the facility specifically directs you to.' },
      { question: 'Can express screening guarantee the result sooner?', answer: 'Priority service may reduce waiting time at the centre but does not guarantee laboratory reporting or immigration approval timing.' },
      { question: 'Are the medical and ID biometrics at the same location?', answer: 'They are separate authority steps and may be at different locations. Check each appointment confirmation carefully.' },
    ],
    interaction: 'locations',
    formTitle: 'Find the right appointment location',
    formDescription: 'Tell us which step you need—DHA medical fitness or ICP biometrics—and your Dubai area.',
  },
  'Visa Validity Checker': {
    title: 'Visa Validity Checker',
    eyebrow: 'Check official immigration status',
    description: 'Use the correct ICP or GDRFA portal to verify a visa, understand where to find the reference number and estimate overstay exposure.',
    heroMetric: 'CHECK OFFICIAL',
    heroLabel: 'ICP and GDRFA government channels',
    introTitle: 'Always verify status with the authority that issued the visa',
    intro: 'Use ICP for federal immigration files and GDRFA for Dubai-issued files. Third-party guidance cannot confirm a live government record. Have the passport and visa or application details ready, and verify grace-period dates directly before booking travel.',
    metrics: [{ value: 'ICP', label: 'federal emirates and file status' }, { value: 'GDRFA Dubai', label: 'Dubai-issued residence and entry permits' }, { value: 'AED 50/day', label: 'commonly cited overstay fine after grace; verify live amount' }],
    highlights: [
      { title: 'ICP status', description: 'Use the ICP Smart Services portal for visa validity and application information for federal files.' },
      { title: 'GDRFA Dubai status', description: 'Dubai visa holders should use GDRFA Dubai’s official website or app for their file and fine information.' },
      { title: 'Overstay prevention', description: 'Grace periods differ by visa and cancellation reason. Confirm the final permitted date on the official record before travel.' },
    ],
    processTitle: 'How to check your UAE visa online',
    process: [
      { title: 'Identify the issuing authority', detail: 'Check whether the visa was issued by Dubai GDRFA or the federal ICP system.' },
      { title: 'Open the official portal', detail: 'Follow the ICP or GDRFA links below and choose the visa / file validity inquiry service.' },
      { title: 'Enter the requested details', detail: 'Use the passport, file, UID or application data requested by the portal; do not share OTPs or UAE Pass credentials.' },
      { title: 'Save the result and next date', detail: 'Record the official expiry and grace-period end date; contact the authority if the status or fine looks incorrect.' },
    ],
    documentsTitle: 'Have these details ready',
    documents: ['Passport number, nationality and passport expiry date', 'Visa copy or application / file number if available', 'Unified number (UID) where requested by the official service', 'Emirate / issuing authority and visa type', 'Cancellation date and exit record for a cancelled residence visa', 'Official result reference and payment receipt if a fine is displayed'],
    faqs: [
      { question: 'Which site should I use for a Dubai visa?', answer: 'Use GDRFA Dubai’s official service channels for a visa issued by Dubai. Use ICP for federal files and visas issued by other emirates.' },
      { question: 'Can I check a visa using only a passport number?', answer: 'The official portal may ask for additional identity and file details. Use only the fields shown on the official government service.' },
      { question: 'How much is the overstay fine?', answer: 'A commonly cited rate is AED 50 per day after the applicable grace period, but rates and grace periods can change by visa category. Confirm the exact live amount with the issuing authority.' },
      { question: 'Does this page access government records?', answer: 'No. This page provides instructions and a rough fine calculator only. It does not submit passport data or retrieve a live immigration result.' },
    ],
    interaction: 'visa-checker',
    formTitle: 'Need help understanding an official result?',
    formDescription: 'Share the issuing emirate, visa type and the wording of the notice. Never send passwords, OTPs or full passport images in an initial inquiry.',
  },
  'ILOE Insurance': {
    title: 'ILOE Insurance',
    eyebrow: 'UAE unemployment insurance',
    description: 'Understand mandatory ILOE cover, compare salary-based premiums, estimate a possible claim benefit and learn how to check your policy and fines securely.',
    heroMetric: '60%',
    heroLabel: 'of average basic salary, subject to category caps and eligibility',
    introTitle: 'Know your cover before you need to claim',
    intro: 'Involuntary Loss of Employment (ILOE) insurance provides a temporary benefit after qualifying involuntary job loss. Most private-sector and federal-government employees are required to subscribe, while specified groups are exempt. Keep premiums current and verify your live status directly with the official ILOE service.',
    metrics: [{ value: 'AED 5/mo', label: 'Category A: basic salary up to AED 16,000' }, { value: 'AED 10/mo', label: 'Category B: basic salary above AED 16,000' }, { value: 'AED 400 + 200', label: 'subscription and late-premium fines, where applicable' }],
    highlights: [
      { title: 'Category 1 / A', description: 'Basic salary up to AED 16,000: premium is AED 5 per month plus VAT; annual, quarterly and monthly payment options may be offered.' },
      { title: 'Category 2 / B', description: 'Basic salary above AED 16,000: premium is AED 10 per month plus VAT; confirm the current plan and payment channel.' },
      { title: 'Claim requirements', description: 'Common guidance includes 12 consecutive months of subscription, qualifying involuntary job loss and submitting a claim within 30 days.' },
      { title: 'Status and penalty checks', description: 'Review your own policy, receipts and any recorded fines on the official portal. Do not share Emirates ID details or login codes in an informal inquiry.' },
    ],
    processTitle: 'Subscribe and keep the policy active',
    process: [
      { title: 'Confirm your category', detail: 'Use your basic salary—not total package—to identify the applicable category and premium.' },
      { title: 'Subscribe through an approved channel', detail: 'Use the official ILOE website, app, exchange, kiosk or other approved channel.' },
      { title: 'Choose a payment frequency', detail: 'Monthly, quarterly or annual instalments may be available. Keep receipts and check that automatic payments do not expire or fail.' },
      { title: 'Check status and fines', detail: 'Review policy and penalty status with the official checker; resolve any recorded amount using the official payment options.' },
    ],
    documentsTitle: 'Before checking or subscribing',
    documents: ['Emirates ID and contact details for the official ILOE check', 'Basic monthly salary to identify the correct category', 'Employer and sector details to confirm mandatory status', 'Valid email and UAE mobile number for policy notices', 'Payment card or approved-channel information', 'Policy number and subscription receipts for an existing plan'],
    table: {
      title: 'ILOE plan comparison',
      caption: 'Premiums below are the commonly published base amounts and exclude VAT. Check the official insurer / ILOE portal for current pricing and eligibility.',
      columns: ['Category', 'Monthly basic salary', 'Base premium', 'Maximum monthly benefit'],
      rows: [
        ['Category A / 1', 'AED 16,000 or less', 'AED 5 + VAT', 'Up to AED 10,000 for up to 3 months'],
        ['Category B / 2', 'Above AED 16,000', 'AED 10 + VAT', 'Up to AED 20,000 for up to 3 months'],
      ],
    },
    faqs: [
      { question: 'Who is exempt from ILOE?', answer: 'Investors / business owners, domestic workers, employees under 18 and certain pensioners who take a new job are generally exempt. Verify your employment category.' },
      { question: 'What are the common fines?', answer: 'The current cited penalties are AED 400 for failing to subscribe and AED 200 for premiums unpaid for more than three months. Check the official ILOE portal for your account.' },
      { question: 'How much compensation can I receive?', answer: 'Eligible claims are generally calculated at 60% of average basic salary over the preceding six months, subject to a monthly category cap and a maximum of three months per claim.' },
      { question: 'What conditions apply to an ILOE claim?', answer: 'Commonly published guidance refers to at least 12 consecutive months of subscription, qualifying involuntary job loss and filing within 30 days of the last working day. The insurer assesses the policy and evidence.' },
      { question: 'Does resignation qualify for a claim?', answer: 'The scheme is for qualifying involuntary job loss. Resignation and dismissal for cause are generally not covered; the insurer reviews the circumstances and decides the claim.' },
      { question: 'How can I check my subscription or fine?', answer: 'Use the official ILOE portal and its identity-verification process. This page does not retrieve government or insurer account data.' },
      { question: 'Can I pay monthly or annually?', answer: 'Payment schedules can include monthly, quarterly or annual options depending on the approved channel. Check the current options and keep your payment confirmation.' },
    ],
    interaction: 'iloe',
    formTitle: 'Get help understanding ILOE requirements',
    formDescription: 'Use the official ILOE channel for live account status. For general guidance, share your employment category only—never include your Emirates ID number, password or OTP.',
  },
};
